/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const AttendingStatus = {
	ATTENDING: 'ATTENDING',
	NOT_ATTENDING: 'NOT_ATTENDING',
	UNSURE: 'UNSURE',
	NO_RESPONSE: 'NO_RESPONSE',
} as const

export type AttendingStatus = (typeof AttendingStatus)[keyof typeof AttendingStatus]

export const ProductType = {
	ALCOHOL: 'ALCOHOL',
	FOOD: 'FOOD',
	OTHER: 'OTHER',
} as const

export type ProductType = (typeof ProductType)[keyof typeof ProductType]

export const FinancialPersonType = {
	USER: 'USER',
	GROUP: 'GROUP',
	ACTIVITY: 'ACTIVITY',
	INVICTUS: 'INVICTUS',
	COMMITTEE: 'COMMITTEE',
	OTHER: 'OTHER',
} as const

export type FinancialPersonType = (typeof FinancialPersonType)[keyof typeof FinancialPersonType]

export const TransactionType = {
	SALDO: 'SALDO',
	BANK: 'BANK',
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]

export const BankTransactionType = {
	TOPUP: 'TOPUP',
	TRANSFER: 'TRANSFER',
	CARD_PAYMENT: 'CARD_PAYMENT',
} as const

export type BankTransactionType = (typeof BankTransactionType)[keyof typeof BankTransactionType]

export const BankTransactionProduct = {
	Savings: 'Savings',
	Current: 'Current',
} as const

export type BankTransactionProduct = (typeof BankTransactionProduct)[keyof typeof BankTransactionProduct]

export const JournalType = {
	SALE: 'SALE',
	PURCHASE: 'PURCHASE',
	DECLARATION: 'DECLARATION',
} as const

export type JournalType = (typeof JournalType)[keyof typeof JournalType]

export const DeclarationStatus = {
	ACCEPTED: 'ACCEPTED',
	DECLINED: 'DECLINED',
	PENDING: 'PENDING',
} as const

export type DeclarationStatus = (typeof DeclarationStatus)[keyof typeof DeclarationStatus]

export const ReceiveMethod = {
	SALDO: 'SALDO',
	ACCOUNT: 'ACCOUNT',
} as const

export type ReceiveMethod = (typeof ReceiveMethod)[keyof typeof ReceiveMethod]

export const LeaderboardTypes = {
	SCORE: 'SCORE',
	COUNT: 'COUNT',
	TIME: 'TIME',
	ADTMEISTER: 'ADTMEISTER',
} as const

export type LeaderboardTypes = (typeof LeaderboardTypes)[keyof typeof LeaderboardTypes]

export const LeaderboardSort = {
	ASC: 'ASC',
	DESC: 'DESC',
} as const

export type LeaderboardSort = (typeof LeaderboardSort)[keyof typeof LeaderboardSort]

export const NotificationType = {
	NotificationGeneric: 'NotificationGeneric',
	ActivityNew: 'ActivityNew',
	ActivityChangedDate: 'ActivityChangedDate',
	ActivityFillInReminder: 'ActivityFillInReminder',
	TagActivityDescription: 'TagActivityDescription',
	TagPhoto: 'TagPhoto',
	TagCommentPhoto: 'TagCommentPhoto',
	TagCommentActivity: 'TagCommentActivity',
	StrafbakCreate: 'StrafbakCreate',
	StrafbakDouble: 'StrafbakDouble',
	StrafbakkenMaster: 'StrafbakkenMaster',
	LeaderboardGotBeaten: 'LeaderboardGotBeaten',
	LeaderboardNew: 'LeaderboardNew',
	OngeveerDeclarationApproved: 'OngeveerDeclarationApproved',
	OngeveerDeclarationDisapproved: 'OngeveerDeclarationDisapproved',
	AdminNoPersonalEmail: 'AdminNoPersonalEmail',
	AdminSettingNotFound: 'AdminSettingNotFound',
	AdminNotificationDeliveryFailed: 'AdminNotificationDeliveryFailed',
	AdminNotificationContructionFailed: 'AdminNotificationContructionFailed',
	AdminError: 'AdminError',
	AdminShitpost: 'AdminShitpost',
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]
