FROM oven/bun:1.3.6

WORKDIR /ibs3

COPY backend/* .
COPY emails ./emails/

RUN bun 

# COPY backend/* ./
# COPY prisma ./prisma/
# COPY emails ./emails/

# RUN apk add openssl
# RUN npm install
# RUN npx prisma generate
# RUN npm install -g typescript
# RUN npm install node-cron

# RUN tsc

CMD ["bun", "--bun", "run", "index.ts"]