# Docker compose for testing, with mariadb, redis and mongo
version: "3.9"
name: ibs3_test

volumes:
  db:
  fs:

services:
  mariadb:
    image: mariadb
    ports:
      - "4401:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ibs3_test
      MYSQL_ROOT_HOST: "%"

  redis:
    image: redis
    ports:
      - "4402:6379"

  mongodb:
    image: mongo
    volumes:
      - fs:/data/db
    ports:
      - "4403:27017"