/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser'

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal

export const NullTypes = {
	DbNull: runtime.NullTypes.DbNull as new (secret: never) => typeof runtime.DbNull,
	JsonNull: runtime.NullTypes.JsonNull as new (secret: never) => typeof runtime.JsonNull,
	AnyNull: runtime.NullTypes.AnyNull as new (secret: never) => typeof runtime.AnyNull,
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull

export const ModelName = {
	Settings: 'Settings',
	BasePreference: 'BasePreference',
	Preference: 'Preference',
	User: 'User',
	Account: 'Account',
	UnlinkedAccount: 'UnlinkedAccount',
	Session: 'Session',
	AccessToken: 'AccessToken',
	Committee: 'Committee',
	CommitteeMember: 'CommitteeMember',
	Strafbak: 'Strafbak',
	Maluspunt: 'Maluspunt',
	Activity: 'Activity',
	ActivityLocation: 'ActivityLocation',
	Attending: 'Attending',
	Ledger: 'Ledger',
	ProductCategory: 'ProductCategory',
	Product: 'Product',
	FinancialPerson: 'FinancialPerson',
	FinancialPersonDataUser: 'FinancialPersonDataUser',
	FinancialGroup: 'FinancialGroup',
	FinancialGroupPersonElement: 'FinancialGroupPersonElement',
	FinancialPersonDataActivity: 'FinancialPersonDataActivity',
	FinancialPersonDataCommittee: 'FinancialPersonDataCommittee',
	FinancialPersonDataOther: 'FinancialPersonDataOther',
	Transaction: 'Transaction',
	TransactionMatchRow: 'TransactionMatchRow',
	SaldoTransaction: 'SaldoTransaction',
	BankTransaction: 'BankTransaction',
	Streeplijst: 'Streeplijst',
	Journal: 'Journal',
	DeclarationData: 'DeclarationData',
	JournalRow: 'JournalRow',
	Link: 'Link',
	LinkClick: 'LinkClick',
	EmailAlias: 'EmailAlias',
	EmailAliasCommittee: 'EmailAliasCommittee',
	EmailAliasUser: 'EmailAliasUser',
	EmailContact: 'EmailContact',
	ClickSession: 'ClickSession',
	Track: 'Track',
	TrackReaction: 'TrackReaction',
	Photo: 'Photo',
	PhotoTag: 'PhotoTag',
	PhotosWithTags: 'PhotosWithTags',
	PhotoPersonTag: 'PhotoPersonTag',
	PhotoRating: 'PhotoRating',
	Comment: 'Comment',
	Leaderboard: 'Leaderboard',
	LeaderboardEntry: 'LeaderboardEntry',
	LeaderboardChallenger: 'LeaderboardChallenger',
	LeaderboardChallengerUser: 'LeaderboardChallengerUser',
	File: 'File',
	Job: 'Job',
	Notification: 'Notification',
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
	ReadUncommitted: 'ReadUncommitted',
	ReadCommitted: 'ReadCommitted',
	RepeatableRead: 'RepeatableRead',
	Serializable: 'Serializable',
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]

export const SettingsScalarFieldEnum = {
	id: 'id',
	name: 'name',
	description: 'description',
	value: 'value',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]

export const BasePreferenceScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	key: 'key',
	defaultValue: 'defaultValue',
	description: 'description',
} as const

export type BasePreferenceScalarFieldEnum = (typeof BasePreferenceScalarFieldEnum)[keyof typeof BasePreferenceScalarFieldEnum]

export const PreferenceScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	userId: 'userId',
	baseId: 'baseId',
	value: 'value',
} as const

export type PreferenceScalarFieldEnum = (typeof PreferenceScalarFieldEnum)[keyof typeof PreferenceScalarFieldEnum]

export const UserScalarFieldEnum = {
	id: 'id',
	isActive: 'isActive',
	firstName: 'firstName',
	lastName: 'lastName',
	ldapId: 'ldapId',
	email: 'email',
	personalEmail: 'personalEmail',
	nickname: 'nickname',
	profilePicture: 'profilePicture',
	birthDate: 'birthDate',
	phone: 'phone',
	firstDrink: 'firstDrink',
	becameFeut: 'becameFeut',
	becameMember: 'becameMember',
	lastLoggedin: 'lastLoggedin',
	preferredTheme: 'preferredTheme',
	accessDisabled: 'accessDisabled',
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]

export const AccountScalarFieldEnum = {
	id: 'id',
	userId: 'userId',
	type: 'type',
	provider: 'provider',
	providerAccountId: 'providerAccountId',
	refresh_token: 'refresh_token',
	access_token: 'access_token',
	expires_at: 'expires_at',
	token_type: 'token_type',
	scope: 'scope',
	id_token: 'id_token',
	session_state: 'session_state',
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]

export const UnlinkedAccountScalarFieldEnum = {
	id: 'id',
	providerAccountId: 'providerAccountId',
	createdAt: 'createdAt',
} as const

export type UnlinkedAccountScalarFieldEnum = (typeof UnlinkedAccountScalarFieldEnum)[keyof typeof UnlinkedAccountScalarFieldEnum]

export const SessionScalarFieldEnum = {
	id: 'id',
	sessionToken: 'sessionToken',
	userId: 'userId',
	expires: 'expires',
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]

export const AccessTokenScalarFieldEnum = {
	token: 'token',
	name: 'name',
	type: 'type',
	userId: 'userId',
	lastUsed: 'lastUsed',
} as const

export type AccessTokenScalarFieldEnum = (typeof AccessTokenScalarFieldEnum)[keyof typeof AccessTokenScalarFieldEnum]

export const CommitteeScalarFieldEnum = {
	id: 'id',
	name: 'name',
	ldapId: 'ldapId',
	isActive: 'isActive',
} as const

export type CommitteeScalarFieldEnum = (typeof CommitteeScalarFieldEnum)[keyof typeof CommitteeScalarFieldEnum]

export const CommitteeMemberScalarFieldEnum = {
	id: 'id',
	committeeId: 'committeeId',
	userId: 'userId',
	joinDate: 'joinDate',
	leaveDate: 'leaveDate',
	function: 'function',
} as const

export type CommitteeMemberScalarFieldEnum = (typeof CommitteeMemberScalarFieldEnum)[keyof typeof CommitteeMemberScalarFieldEnum]

export const StrafbakScalarFieldEnum = {
	id: 'id',
	giverId: 'giverId',
	receiverId: 'receiverId',
	reason: 'reason',
	dateCreated: 'dateCreated',
	dateDeleted: 'dateDeleted',
	location: 'location',
} as const

export type StrafbakScalarFieldEnum = (typeof StrafbakScalarFieldEnum)[keyof typeof StrafbakScalarFieldEnum]

export const MaluspuntScalarFieldEnum = {
	id: 'id',
	giverId: 'giverId',
	receiverId: 'receiverId',
	reason: 'reason',
	dateCreated: 'dateCreated',
	amount: 'amount',
} as const

export type MaluspuntScalarFieldEnum = (typeof MaluspuntScalarFieldEnum)[keyof typeof MaluspuntScalarFieldEnum]

export const ActivityScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	createdById: 'createdById',
	name: 'name',
	description: 'description',
	startTime: 'startTime',
	endTime: 'endTime',
	locationId: 'locationId',
	membersOnly: 'membersOnly',
	committeeId: 'committeeId',
	photo: 'photo',
	url: 'url',
	isActive: 'isActive',
} as const

export type ActivityScalarFieldEnum = (typeof ActivityScalarFieldEnum)[keyof typeof ActivityScalarFieldEnum]

export const ActivityLocationScalarFieldEnum = {
	id: 'id',
	name: 'name',
	adress: 'adress',
	country: 'country',
	postalCode: 'postalCode',
	city: 'city',
	description: 'description',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	isActive: 'isActive',
} as const

export type ActivityLocationScalarFieldEnum = (typeof ActivityLocationScalarFieldEnum)[keyof typeof ActivityLocationScalarFieldEnum]

export const AttendingScalarFieldEnum = {
	id: 'id',
	userId: 'userId',
	activityId: 'activityId',
	status: 'status',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	isActive: 'isActive',
} as const

export type AttendingScalarFieldEnum = (typeof AttendingScalarFieldEnum)[keyof typeof AttendingScalarFieldEnum]

export const LedgerScalarFieldEnum = {
	id: 'id',
	name: 'name',
	description: 'description',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	isActive: 'isActive',
} as const

export type LedgerScalarFieldEnum = (typeof LedgerScalarFieldEnum)[keyof typeof LedgerScalarFieldEnum]

export const ProductCategoryScalarFieldEnum = {
	id: 'id',
	name: 'name',
	description: 'description',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	isActive: 'isActive',
} as const

export type ProductCategoryScalarFieldEnum = (typeof ProductCategoryScalarFieldEnum)[keyof typeof ProductCategoryScalarFieldEnum]

export const ProductScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	name: 'name',
	description: 'description',
	price: 'price',
	productType: 'productType',
	data: 'data',
	categoryId: 'categoryId',
	isActive: 'isActive',
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]

export const FinancialPersonScalarFieldEnum = {
	id: 'id',
	type: 'type',
	name: 'name',
	balance: 'balance',
	isActive: 'isActive',
} as const

export type FinancialPersonScalarFieldEnum = (typeof FinancialPersonScalarFieldEnum)[keyof typeof FinancialPersonScalarFieldEnum]

export const FinancialPersonDataUserScalarFieldEnum = {
	personId: 'personId',
	userId: 'userId',
	iban: 'iban',
} as const

export type FinancialPersonDataUserScalarFieldEnum =
	(typeof FinancialPersonDataUserScalarFieldEnum)[keyof typeof FinancialPersonDataUserScalarFieldEnum]

export const FinancialGroupScalarFieldEnum = {
	personId: 'personId',
} as const

export type FinancialGroupScalarFieldEnum = (typeof FinancialGroupScalarFieldEnum)[keyof typeof FinancialGroupScalarFieldEnum]

export const FinancialGroupPersonElementScalarFieldEnum = {
	groupId: 'groupId',
	personId: 'personId',
} as const

export type FinancialGroupPersonElementScalarFieldEnum =
	(typeof FinancialGroupPersonElementScalarFieldEnum)[keyof typeof FinancialGroupPersonElementScalarFieldEnum]

export const FinancialPersonDataActivityScalarFieldEnum = {
	personId: 'personId',
	activityId: 'activityId',
} as const

export type FinancialPersonDataActivityScalarFieldEnum =
	(typeof FinancialPersonDataActivityScalarFieldEnum)[keyof typeof FinancialPersonDataActivityScalarFieldEnum]

export const FinancialPersonDataCommitteeScalarFieldEnum = {
	personId: 'personId',
	committeeId: 'committeeId',
} as const

export type FinancialPersonDataCommitteeScalarFieldEnum =
	(typeof FinancialPersonDataCommitteeScalarFieldEnum)[keyof typeof FinancialPersonDataCommitteeScalarFieldEnum]

export const FinancialPersonDataOtherScalarFieldEnum = {
	personId: 'personId',
	description: 'description',
	email: 'email',
	address: 'address',
	postalCode: 'postalCode',
	city: 'city',
	iban: 'iban',
} as const

export type FinancialPersonDataOtherScalarFieldEnum =
	(typeof FinancialPersonDataOtherScalarFieldEnum)[keyof typeof FinancialPersonDataOtherScalarFieldEnum]

export const TransactionScalarFieldEnum = {
	id: 'id',
	type: 'type',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]

export const TransactionMatchRowScalarFieldEnum = {
	id: 'id',
	description: 'description',
	amount: 'amount',
	transactionId: 'transactionId',
	saldoTransactionId: 'saldoTransactionId',
	journalId: 'journalId',
} as const

export type TransactionMatchRowScalarFieldEnum =
	(typeof TransactionMatchRowScalarFieldEnum)[keyof typeof TransactionMatchRowScalarFieldEnum]

export const SaldoTransactionScalarFieldEnum = {
	id: 'id',
	description: 'description',
	price: 'price',
	fromId: 'fromId',
	toId: 'toId',
	transactionId: 'transactionId',
} as const

export type SaldoTransactionScalarFieldEnum = (typeof SaldoTransactionScalarFieldEnum)[keyof typeof SaldoTransactionScalarFieldEnum]

export const BankTransactionScalarFieldEnum = {
	id: 'id',
	ref: 'ref',
	type: 'type',
	product: 'product',
	startedDate: 'startedDate',
	completedDate: 'completedDate',
	description: 'description',
	amount: 'amount',
	fee: 'fee',
	relationId: 'relationId',
	transactionId: 'transactionId',
} as const

export type BankTransactionScalarFieldEnum = (typeof BankTransactionScalarFieldEnum)[keyof typeof BankTransactionScalarFieldEnum]

export const StreeplijstScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	startDate: 'startDate',
	endDate: 'endDate',
	userId: 'userId',
	notes: 'notes',
} as const

export type StreeplijstScalarFieldEnum = (typeof StreeplijstScalarFieldEnum)[keyof typeof StreeplijstScalarFieldEnum]

export const JournalScalarFieldEnum = {
	id: 'id',
	ref: 'ref',
	date: 'date',
	termsOfPayment: 'termsOfPayment',
	tav: 'tav',
	description: 'description',
	type: 'type',
	relationId: 'relationId',
	treasurerId: 'treasurerId',
	streeplijstId: 'streeplijstId',
} as const

export type JournalScalarFieldEnum = (typeof JournalScalarFieldEnum)[keyof typeof JournalScalarFieldEnum]

export const DeclarationDataScalarFieldEnum = {
	id: 'id',
	methodOfPayment: 'methodOfPayment',
	receiveMethod: 'receiveMethod',
	status: 'status',
	iban: 'iban',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	askedAmount: 'askedAmount',
	reason: 'reason',
	financialPersonId: 'financialPersonId',
	journalId: 'journalId',
} as const

export type DeclarationDataScalarFieldEnum = (typeof DeclarationDataScalarFieldEnum)[keyof typeof DeclarationDataScalarFieldEnum]

export const JournalRowScalarFieldEnum = {
	id: 'id',
	amount: 'amount',
	price: 'price',
	description: 'description',
	productId: 'productId',
	ledgerId: 'ledgerId',
	journalId: 'journalId',
} as const

export type JournalRowScalarFieldEnum = (typeof JournalRowScalarFieldEnum)[keyof typeof JournalRowScalarFieldEnum]

export const LinkScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	link: 'link',
	shortLink: 'shortLink',
	userId: 'userId',
} as const

export type LinkScalarFieldEnum = (typeof LinkScalarFieldEnum)[keyof typeof LinkScalarFieldEnum]

export const LinkClickScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	linkId: 'linkId',
	userId: 'userId',
} as const

export type LinkClickScalarFieldEnum = (typeof LinkClickScalarFieldEnum)[keyof typeof LinkClickScalarFieldEnum]

export const EmailAliasScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	alias: 'alias',
} as const

export type EmailAliasScalarFieldEnum = (typeof EmailAliasScalarFieldEnum)[keyof typeof EmailAliasScalarFieldEnum]

export const EmailAliasCommitteeScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	emailAliasId: 'emailAliasId',
	committeeId: 'committeeId',
} as const

export type EmailAliasCommitteeScalarFieldEnum =
	(typeof EmailAliasCommitteeScalarFieldEnum)[keyof typeof EmailAliasCommitteeScalarFieldEnum]

export const EmailAliasUserScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	emailAliasId: 'emailAliasId',
	userId: 'userId',
} as const

export type EmailAliasUserScalarFieldEnum = (typeof EmailAliasUserScalarFieldEnum)[keyof typeof EmailAliasUserScalarFieldEnum]

export const EmailContactScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	address: 'address',
	emailAliasId: 'emailAliasId',
} as const

export type EmailContactScalarFieldEnum = (typeof EmailContactScalarFieldEnum)[keyof typeof EmailContactScalarFieldEnum]

export const ClickSessionScalarFieldEnum = {
	id: 'id',
	userId: 'userId',
	amount: 'amount',
	startTime: 'startTime',
	endTime: 'endTime',
} as const

export type ClickSessionScalarFieldEnum = (typeof ClickSessionScalarFieldEnum)[keyof typeof ClickSessionScalarFieldEnum]

export const TrackScalarFieldEnum = {
	id: 'id',
	inPlaylist: 'inPlaylist',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
} as const

export type TrackScalarFieldEnum = (typeof TrackScalarFieldEnum)[keyof typeof TrackScalarFieldEnum]

export const TrackReactionScalarFieldEnum = {
	userId: 'userId',
	trackId: 'trackId',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	liked: 'liked',
} as const

export type TrackReactionScalarFieldEnum = (typeof TrackReactionScalarFieldEnum)[keyof typeof TrackReactionScalarFieldEnum]

export const PhotoScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	date: 'date',
	visible: 'visible',
	fileId: 'fileId',
	description: 'description',
	uploaderId: 'uploaderId',
	creatorId: 'creatorId',
	activityPhotoId: 'activityPhotoId',
} as const

export type PhotoScalarFieldEnum = (typeof PhotoScalarFieldEnum)[keyof typeof PhotoScalarFieldEnum]

export const PhotoTagScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	name: 'name',
} as const

export type PhotoTagScalarFieldEnum = (typeof PhotoTagScalarFieldEnum)[keyof typeof PhotoTagScalarFieldEnum]

export const PhotosWithTagsScalarFieldEnum = {
	photoId: 'photoId',
	photoTagId: 'photoTagId',
	assignedById: 'assignedById',
} as const

export type PhotosWithTagsScalarFieldEnum = (typeof PhotosWithTagsScalarFieldEnum)[keyof typeof PhotosWithTagsScalarFieldEnum]

export const PhotoPersonTagScalarFieldEnum = {
	taggerId: 'taggerId',
	photoId: 'photoId',
	userId: 'userId',
} as const

export type PhotoPersonTagScalarFieldEnum = (typeof PhotoPersonTagScalarFieldEnum)[keyof typeof PhotoPersonTagScalarFieldEnum]

export const PhotoRatingScalarFieldEnum = {
	rating: 'rating',
	photoId: 'photoId',
	userId: 'userId',
} as const

export type PhotoRatingScalarFieldEnum = (typeof PhotoRatingScalarFieldEnum)[keyof typeof PhotoRatingScalarFieldEnum]

export const CommentScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	comment: 'comment',
	commenterId: 'commenterId',
	photoId: 'photoId',
	activityId: 'activityId',
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]

export const LeaderboardScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	pinned: 'pinned',
	name: 'name',
	description: 'description',
	type: 'type',
	sortBy: 'sortBy',
	opensAt: 'opensAt',
	closesAt: 'closesAt',
} as const

export type LeaderboardScalarFieldEnum = (typeof LeaderboardScalarFieldEnum)[keyof typeof LeaderboardScalarFieldEnum]

export const LeaderboardEntryScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	leaderboardId: 'leaderboardId',
	userId: 'userId',
	challengerId: 'challengerId',
	value: 'value',
} as const

export type LeaderboardEntryScalarFieldEnum = (typeof LeaderboardEntryScalarFieldEnum)[keyof typeof LeaderboardEntryScalarFieldEnum]

export const LeaderboardChallengerScalarFieldEnum = {
	id: 'id',
	firstName: 'firstName',
	lastName: 'lastName',
} as const

export type LeaderboardChallengerScalarFieldEnum =
	(typeof LeaderboardChallengerScalarFieldEnum)[keyof typeof LeaderboardChallengerScalarFieldEnum]

export const LeaderboardChallengerUserScalarFieldEnum = {
	challengerId: 'challengerId',
	userId: 'userId',
} as const

export type LeaderboardChallengerUserScalarFieldEnum =
	(typeof LeaderboardChallengerUserScalarFieldEnum)[keyof typeof LeaderboardChallengerUserScalarFieldEnum]

export const FileScalarFieldEnum = {
	id: 'id',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	filename: 'filename',
	deletedAt: 'deletedAt',
	deleted: 'deleted',
	uploaderId: 'uploaderId',
	journalId: 'journalId',
} as const

export type FileScalarFieldEnum = (typeof FileScalarFieldEnum)[keyof typeof FileScalarFieldEnum]

export const JobScalarFieldEnum = {
	name: 'name',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	data: 'data',
	type: 'type',
	finished: 'finished',
	completedAt: 'completedAt',
	result: 'result',
} as const

export type JobScalarFieldEnum = (typeof JobScalarFieldEnum)[keyof typeof JobScalarFieldEnum]

export const NotificationScalarFieldEnum = {
	id: 'id',
	title: 'title',
	body: 'body',
	type: 'type',
	sent: 'sent',
	userId: 'userId',
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]

export const SortOrder = {
	asc: 'asc',
	desc: 'desc',
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const JsonNullValueInput = {
	JsonNull: 'JsonNull',
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]

export const SettingsOrderByRelevanceFieldEnum = {
	name: 'name',
	description: 'description',
	value: 'value',
} as const

export type SettingsOrderByRelevanceFieldEnum = (typeof SettingsOrderByRelevanceFieldEnum)[keyof typeof SettingsOrderByRelevanceFieldEnum]

export const BasePreferenceOrderByRelevanceFieldEnum = {
	key: 'key',
	description: 'description',
} as const

export type BasePreferenceOrderByRelevanceFieldEnum =
	(typeof BasePreferenceOrderByRelevanceFieldEnum)[keyof typeof BasePreferenceOrderByRelevanceFieldEnum]

export const NullsOrder = {
	first: 'first',
	last: 'last',
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

export const UserOrderByRelevanceFieldEnum = {
	firstName: 'firstName',
	lastName: 'lastName',
	ldapId: 'ldapId',
	email: 'email',
	personalEmail: 'personalEmail',
	nickname: 'nickname',
	profilePicture: 'profilePicture',
	phone: 'phone',
	preferredTheme: 'preferredTheme',
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]

export const AccountOrderByRelevanceFieldEnum = {
	id: 'id',
	type: 'type',
	provider: 'provider',
	providerAccountId: 'providerAccountId',
	refresh_token: 'refresh_token',
	access_token: 'access_token',
	token_type: 'token_type',
	scope: 'scope',
	id_token: 'id_token',
	session_state: 'session_state',
} as const

export type AccountOrderByRelevanceFieldEnum = (typeof AccountOrderByRelevanceFieldEnum)[keyof typeof AccountOrderByRelevanceFieldEnum]

export const UnlinkedAccountOrderByRelevanceFieldEnum = {
	id: 'id',
	providerAccountId: 'providerAccountId',
} as const

export type UnlinkedAccountOrderByRelevanceFieldEnum =
	(typeof UnlinkedAccountOrderByRelevanceFieldEnum)[keyof typeof UnlinkedAccountOrderByRelevanceFieldEnum]

export const SessionOrderByRelevanceFieldEnum = {
	id: 'id',
	sessionToken: 'sessionToken',
} as const

export type SessionOrderByRelevanceFieldEnum = (typeof SessionOrderByRelevanceFieldEnum)[keyof typeof SessionOrderByRelevanceFieldEnum]

export const AccessTokenOrderByRelevanceFieldEnum = {
	token: 'token',
	name: 'name',
	type: 'type',
} as const

export type AccessTokenOrderByRelevanceFieldEnum =
	(typeof AccessTokenOrderByRelevanceFieldEnum)[keyof typeof AccessTokenOrderByRelevanceFieldEnum]

export const CommitteeOrderByRelevanceFieldEnum = {
	name: 'name',
	ldapId: 'ldapId',
} as const

export type CommitteeOrderByRelevanceFieldEnum =
	(typeof CommitteeOrderByRelevanceFieldEnum)[keyof typeof CommitteeOrderByRelevanceFieldEnum]

export const CommitteeMemberOrderByRelevanceFieldEnum = {
	function: 'function',
} as const

export type CommitteeMemberOrderByRelevanceFieldEnum =
	(typeof CommitteeMemberOrderByRelevanceFieldEnum)[keyof typeof CommitteeMemberOrderByRelevanceFieldEnum]

export const StrafbakOrderByRelevanceFieldEnum = {
	reason: 'reason',
	location: 'location',
} as const

export type StrafbakOrderByRelevanceFieldEnum = (typeof StrafbakOrderByRelevanceFieldEnum)[keyof typeof StrafbakOrderByRelevanceFieldEnum]

export const MaluspuntOrderByRelevanceFieldEnum = {
	reason: 'reason',
} as const

export type MaluspuntOrderByRelevanceFieldEnum =
	(typeof MaluspuntOrderByRelevanceFieldEnum)[keyof typeof MaluspuntOrderByRelevanceFieldEnum]

export const ActivityOrderByRelevanceFieldEnum = {
	name: 'name',
	description: 'description',
	photo: 'photo',
	url: 'url',
} as const

export type ActivityOrderByRelevanceFieldEnum = (typeof ActivityOrderByRelevanceFieldEnum)[keyof typeof ActivityOrderByRelevanceFieldEnum]

export const ActivityLocationOrderByRelevanceFieldEnum = {
	name: 'name',
	adress: 'adress',
	country: 'country',
	postalCode: 'postalCode',
	city: 'city',
	description: 'description',
} as const

export type ActivityLocationOrderByRelevanceFieldEnum =
	(typeof ActivityLocationOrderByRelevanceFieldEnum)[keyof typeof ActivityLocationOrderByRelevanceFieldEnum]

export const LedgerOrderByRelevanceFieldEnum = {
	name: 'name',
	description: 'description',
} as const

export type LedgerOrderByRelevanceFieldEnum = (typeof LedgerOrderByRelevanceFieldEnum)[keyof typeof LedgerOrderByRelevanceFieldEnum]

export const ProductCategoryOrderByRelevanceFieldEnum = {
	name: 'name',
	description: 'description',
} as const

export type ProductCategoryOrderByRelevanceFieldEnum =
	(typeof ProductCategoryOrderByRelevanceFieldEnum)[keyof typeof ProductCategoryOrderByRelevanceFieldEnum]

export const JsonNullValueFilter = {
	DbNull: 'DbNull',
	JsonNull: 'JsonNull',
	AnyNull: 'AnyNull',
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

export const QueryMode = {
	default: 'default',
	insensitive: 'insensitive',
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

export const ProductOrderByRelevanceFieldEnum = {
	name: 'name',
	description: 'description',
} as const

export type ProductOrderByRelevanceFieldEnum = (typeof ProductOrderByRelevanceFieldEnum)[keyof typeof ProductOrderByRelevanceFieldEnum]

export const FinancialPersonOrderByRelevanceFieldEnum = {
	name: 'name',
} as const

export type FinancialPersonOrderByRelevanceFieldEnum =
	(typeof FinancialPersonOrderByRelevanceFieldEnum)[keyof typeof FinancialPersonOrderByRelevanceFieldEnum]

export const FinancialPersonDataUserOrderByRelevanceFieldEnum = {
	iban: 'iban',
} as const

export type FinancialPersonDataUserOrderByRelevanceFieldEnum =
	(typeof FinancialPersonDataUserOrderByRelevanceFieldEnum)[keyof typeof FinancialPersonDataUserOrderByRelevanceFieldEnum]

export const FinancialPersonDataOtherOrderByRelevanceFieldEnum = {
	description: 'description',
	email: 'email',
	address: 'address',
	postalCode: 'postalCode',
	city: 'city',
	iban: 'iban',
} as const

export type FinancialPersonDataOtherOrderByRelevanceFieldEnum =
	(typeof FinancialPersonDataOtherOrderByRelevanceFieldEnum)[keyof typeof FinancialPersonDataOtherOrderByRelevanceFieldEnum]

export const TransactionMatchRowOrderByRelevanceFieldEnum = {
	description: 'description',
} as const

export type TransactionMatchRowOrderByRelevanceFieldEnum =
	(typeof TransactionMatchRowOrderByRelevanceFieldEnum)[keyof typeof TransactionMatchRowOrderByRelevanceFieldEnum]

export const SaldoTransactionOrderByRelevanceFieldEnum = {
	description: 'description',
} as const

export type SaldoTransactionOrderByRelevanceFieldEnum =
	(typeof SaldoTransactionOrderByRelevanceFieldEnum)[keyof typeof SaldoTransactionOrderByRelevanceFieldEnum]

export const BankTransactionOrderByRelevanceFieldEnum = {
	ref: 'ref',
	description: 'description',
} as const

export type BankTransactionOrderByRelevanceFieldEnum =
	(typeof BankTransactionOrderByRelevanceFieldEnum)[keyof typeof BankTransactionOrderByRelevanceFieldEnum]

export const StreeplijstOrderByRelevanceFieldEnum = {
	notes: 'notes',
} as const

export type StreeplijstOrderByRelevanceFieldEnum =
	(typeof StreeplijstOrderByRelevanceFieldEnum)[keyof typeof StreeplijstOrderByRelevanceFieldEnum]

export const JournalOrderByRelevanceFieldEnum = {
	ref: 'ref',
	tav: 'tav',
	description: 'description',
} as const

export type JournalOrderByRelevanceFieldEnum = (typeof JournalOrderByRelevanceFieldEnum)[keyof typeof JournalOrderByRelevanceFieldEnum]

export const DeclarationDataOrderByRelevanceFieldEnum = {
	methodOfPayment: 'methodOfPayment',
	iban: 'iban',
	reason: 'reason',
} as const

export type DeclarationDataOrderByRelevanceFieldEnum =
	(typeof DeclarationDataOrderByRelevanceFieldEnum)[keyof typeof DeclarationDataOrderByRelevanceFieldEnum]

export const JournalRowOrderByRelevanceFieldEnum = {
	description: 'description',
} as const

export type JournalRowOrderByRelevanceFieldEnum =
	(typeof JournalRowOrderByRelevanceFieldEnum)[keyof typeof JournalRowOrderByRelevanceFieldEnum]

export const LinkOrderByRelevanceFieldEnum = {
	link: 'link',
	shortLink: 'shortLink',
} as const

export type LinkOrderByRelevanceFieldEnum = (typeof LinkOrderByRelevanceFieldEnum)[keyof typeof LinkOrderByRelevanceFieldEnum]

export const EmailAliasOrderByRelevanceFieldEnum = {
	alias: 'alias',
} as const

export type EmailAliasOrderByRelevanceFieldEnum =
	(typeof EmailAliasOrderByRelevanceFieldEnum)[keyof typeof EmailAliasOrderByRelevanceFieldEnum]

export const EmailContactOrderByRelevanceFieldEnum = {
	address: 'address',
} as const

export type EmailContactOrderByRelevanceFieldEnum =
	(typeof EmailContactOrderByRelevanceFieldEnum)[keyof typeof EmailContactOrderByRelevanceFieldEnum]

export const TrackOrderByRelevanceFieldEnum = {
	id: 'id',
} as const

export type TrackOrderByRelevanceFieldEnum = (typeof TrackOrderByRelevanceFieldEnum)[keyof typeof TrackOrderByRelevanceFieldEnum]

export const TrackReactionOrderByRelevanceFieldEnum = {
	trackId: 'trackId',
} as const

export type TrackReactionOrderByRelevanceFieldEnum =
	(typeof TrackReactionOrderByRelevanceFieldEnum)[keyof typeof TrackReactionOrderByRelevanceFieldEnum]

export const PhotoOrderByRelevanceFieldEnum = {
	fileId: 'fileId',
	description: 'description',
} as const

export type PhotoOrderByRelevanceFieldEnum = (typeof PhotoOrderByRelevanceFieldEnum)[keyof typeof PhotoOrderByRelevanceFieldEnum]

export const PhotoTagOrderByRelevanceFieldEnum = {
	name: 'name',
} as const

export type PhotoTagOrderByRelevanceFieldEnum = (typeof PhotoTagOrderByRelevanceFieldEnum)[keyof typeof PhotoTagOrderByRelevanceFieldEnum]

export const CommentOrderByRelevanceFieldEnum = {
	comment: 'comment',
} as const

export type CommentOrderByRelevanceFieldEnum = (typeof CommentOrderByRelevanceFieldEnum)[keyof typeof CommentOrderByRelevanceFieldEnum]

export const LeaderboardOrderByRelevanceFieldEnum = {
	id: 'id',
	name: 'name',
	description: 'description',
} as const

export type LeaderboardOrderByRelevanceFieldEnum =
	(typeof LeaderboardOrderByRelevanceFieldEnum)[keyof typeof LeaderboardOrderByRelevanceFieldEnum]

export const LeaderboardEntryOrderByRelevanceFieldEnum = {
	leaderboardId: 'leaderboardId',
	challengerId: 'challengerId',
} as const

export type LeaderboardEntryOrderByRelevanceFieldEnum =
	(typeof LeaderboardEntryOrderByRelevanceFieldEnum)[keyof typeof LeaderboardEntryOrderByRelevanceFieldEnum]

export const LeaderboardChallengerOrderByRelevanceFieldEnum = {
	id: 'id',
	firstName: 'firstName',
	lastName: 'lastName',
} as const

export type LeaderboardChallengerOrderByRelevanceFieldEnum =
	(typeof LeaderboardChallengerOrderByRelevanceFieldEnum)[keyof typeof LeaderboardChallengerOrderByRelevanceFieldEnum]

export const LeaderboardChallengerUserOrderByRelevanceFieldEnum = {
	challengerId: 'challengerId',
} as const

export type LeaderboardChallengerUserOrderByRelevanceFieldEnum =
	(typeof LeaderboardChallengerUserOrderByRelevanceFieldEnum)[keyof typeof LeaderboardChallengerUserOrderByRelevanceFieldEnum]

export const FileOrderByRelevanceFieldEnum = {
	id: 'id',
	filename: 'filename',
} as const

export type FileOrderByRelevanceFieldEnum = (typeof FileOrderByRelevanceFieldEnum)[keyof typeof FileOrderByRelevanceFieldEnum]

export const JobOrderByRelevanceFieldEnum = {
	name: 'name',
	data: 'data',
	type: 'type',
	result: 'result',
} as const

export type JobOrderByRelevanceFieldEnum = (typeof JobOrderByRelevanceFieldEnum)[keyof typeof JobOrderByRelevanceFieldEnum]

export const NotificationOrderByRelevanceFieldEnum = {
	title: 'title',
	body: 'body',
} as const

export type NotificationOrderByRelevanceFieldEnum =
	(typeof NotificationOrderByRelevanceFieldEnum)[keyof typeof NotificationOrderByRelevanceFieldEnum]
