/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Committee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model Committee
 *
 */
export type CommitteeModel = runtime.Types.Result.DefaultSelection<Prisma.$CommitteePayload>

export type AggregateCommittee = {
	_count: CommitteeCountAggregateOutputType | null
	_avg: CommitteeAvgAggregateOutputType | null
	_sum: CommitteeSumAggregateOutputType | null
	_min: CommitteeMinAggregateOutputType | null
	_max: CommitteeMaxAggregateOutputType | null
}

export type CommitteeAvgAggregateOutputType = {
	id: number | null
}

export type CommitteeSumAggregateOutputType = {
	id: number | null
}

export type CommitteeMinAggregateOutputType = {
	id: number | null
	name: string | null
	ldapId: string | null
	isActive: boolean | null
}

export type CommitteeMaxAggregateOutputType = {
	id: number | null
	name: string | null
	ldapId: string | null
	isActive: boolean | null
}

export type CommitteeCountAggregateOutputType = {
	id: number
	name: number
	ldapId: number
	isActive: number
	_all: number
}

export type CommitteeAvgAggregateInputType = {
	id?: true
}

export type CommitteeSumAggregateInputType = {
	id?: true
}

export type CommitteeMinAggregateInputType = {
	id?: true
	name?: true
	ldapId?: true
	isActive?: true
}

export type CommitteeMaxAggregateInputType = {
	id?: true
	name?: true
	ldapId?: true
	isActive?: true
}

export type CommitteeCountAggregateInputType = {
	id?: true
	name?: true
	ldapId?: true
	isActive?: true
	_all?: true
}

export type CommitteeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which Committee to aggregate.
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Committees to fetch.
	 */
	orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.CommitteeWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Committees from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Committees.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned Committees
	 **/
	_count?: true | CommitteeCountAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: CommitteeAvgAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: CommitteeSumAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: CommitteeMinAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: CommitteeMaxAggregateInputType
}

export type GetCommitteeAggregateType<T extends CommitteeAggregateArgs> = {
	[P in keyof T & keyof AggregateCommittee]: P extends '_count' | 'count'
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateCommittee[P]>
		: Prisma.GetScalarType<T[P], AggregateCommittee[P]>
}

export type CommitteeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	where?: Prisma.CommitteeWhereInput
	orderBy?: Prisma.CommitteeOrderByWithAggregationInput | Prisma.CommitteeOrderByWithAggregationInput[]
	by: Prisma.CommitteeScalarFieldEnum[] | Prisma.CommitteeScalarFieldEnum
	having?: Prisma.CommitteeScalarWhereWithAggregatesInput
	take?: number
	skip?: number
	_count?: CommitteeCountAggregateInputType | true
	_avg?: CommitteeAvgAggregateInputType
	_sum?: CommitteeSumAggregateInputType
	_min?: CommitteeMinAggregateInputType
	_max?: CommitteeMaxAggregateInputType
}

export type CommitteeGroupByOutputType = {
	id: number
	name: string
	ldapId: string
	isActive: boolean
	_count: CommitteeCountAggregateOutputType | null
	_avg: CommitteeAvgAggregateOutputType | null
	_sum: CommitteeSumAggregateOutputType | null
	_min: CommitteeMinAggregateOutputType | null
	_max: CommitteeMaxAggregateOutputType | null
}

type GetCommitteeGroupByPayload<T extends CommitteeGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<CommitteeGroupByOutputType, T['by']> & {
			[P in keyof T & keyof CommitteeGroupByOutputType]: P extends '_count'
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], CommitteeGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], CommitteeGroupByOutputType[P]>
		}
	>
>

export type CommitteeWhereInput = {
	AND?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
	OR?: Prisma.CommitteeWhereInput[]
	NOT?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
	id?: Prisma.IntFilter<'Committee'> | number
	name?: Prisma.StringFilter<'Committee'> | string
	ldapId?: Prisma.StringFilter<'Committee'> | string
	isActive?: Prisma.BoolFilter<'Committee'> | boolean
	CommitteeMember?: Prisma.CommitteeMemberListRelationFilter
	Acivity?: Prisma.ActivityListRelationFilter
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeListRelationFilter
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeListRelationFilter
}

export type CommitteeOrderByWithRelationInput = {
	id?: Prisma.SortOrder
	name?: Prisma.SortOrder
	ldapId?: Prisma.SortOrder
	isActive?: Prisma.SortOrder
	CommitteeMember?: Prisma.CommitteeMemberOrderByRelationAggregateInput
	Acivity?: Prisma.ActivityOrderByRelationAggregateInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeOrderByRelationAggregateInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeOrderByRelationAggregateInput
	_relevance?: Prisma.CommitteeOrderByRelevanceInput
}

export type CommitteeWhereUniqueInput = Prisma.AtLeast<
	{
		id?: number
		name?: string
		ldapId?: string
		AND?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
		OR?: Prisma.CommitteeWhereInput[]
		NOT?: Prisma.CommitteeWhereInput | Prisma.CommitteeWhereInput[]
		isActive?: Prisma.BoolFilter<'Committee'> | boolean
		CommitteeMember?: Prisma.CommitteeMemberListRelationFilter
		Acivity?: Prisma.ActivityListRelationFilter
		FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeListRelationFilter
		EmailAliasCommittee?: Prisma.EmailAliasCommitteeListRelationFilter
	},
	'id' | 'name' | 'ldapId'
>

export type CommitteeOrderByWithAggregationInput = {
	id?: Prisma.SortOrder
	name?: Prisma.SortOrder
	ldapId?: Prisma.SortOrder
	isActive?: Prisma.SortOrder
	_count?: Prisma.CommitteeCountOrderByAggregateInput
	_avg?: Prisma.CommitteeAvgOrderByAggregateInput
	_max?: Prisma.CommitteeMaxOrderByAggregateInput
	_min?: Prisma.CommitteeMinOrderByAggregateInput
	_sum?: Prisma.CommitteeSumOrderByAggregateInput
}

export type CommitteeScalarWhereWithAggregatesInput = {
	AND?: Prisma.CommitteeScalarWhereWithAggregatesInput | Prisma.CommitteeScalarWhereWithAggregatesInput[]
	OR?: Prisma.CommitteeScalarWhereWithAggregatesInput[]
	NOT?: Prisma.CommitteeScalarWhereWithAggregatesInput | Prisma.CommitteeScalarWhereWithAggregatesInput[]
	id?: Prisma.IntWithAggregatesFilter<'Committee'> | number
	name?: Prisma.StringWithAggregatesFilter<'Committee'> | string
	ldapId?: Prisma.StringWithAggregatesFilter<'Committee'> | string
	isActive?: Prisma.BoolWithAggregatesFilter<'Committee'> | boolean
}

export type CommitteeCreateInput = {
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUncheckedCreateInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityUncheckedCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUpdateInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeUncheckedUpdateInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUncheckedUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeCreateManyInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
}

export type CommitteeUpdateManyMutationInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CommitteeUncheckedUpdateManyInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type CommitteeOrderByRelevanceInput = {
	fields: Prisma.CommitteeOrderByRelevanceFieldEnum | Prisma.CommitteeOrderByRelevanceFieldEnum[]
	sort: Prisma.SortOrder
	search: string
}

export type CommitteeCountOrderByAggregateInput = {
	id?: Prisma.SortOrder
	name?: Prisma.SortOrder
	ldapId?: Prisma.SortOrder
	isActive?: Prisma.SortOrder
}

export type CommitteeAvgOrderByAggregateInput = {
	id?: Prisma.SortOrder
}

export type CommitteeMaxOrderByAggregateInput = {
	id?: Prisma.SortOrder
	name?: Prisma.SortOrder
	ldapId?: Prisma.SortOrder
	isActive?: Prisma.SortOrder
}

export type CommitteeMinOrderByAggregateInput = {
	id?: Prisma.SortOrder
	name?: Prisma.SortOrder
	ldapId?: Prisma.SortOrder
	isActive?: Prisma.SortOrder
}

export type CommitteeSumOrderByAggregateInput = {
	id?: Prisma.SortOrder
}

export type CommitteeScalarRelationFilter = {
	is?: Prisma.CommitteeWhereInput
	isNot?: Prisma.CommitteeWhereInput
}

export type CommitteeCreateNestedOneWithoutCommitteeMemberInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedCreateWithoutCommitteeMemberInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutCommitteeMemberInput
	connect?: Prisma.CommitteeWhereUniqueInput
}

export type CommitteeUpdateOneRequiredWithoutCommitteeMemberNestedInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedCreateWithoutCommitteeMemberInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutCommitteeMemberInput
	upsert?: Prisma.CommitteeUpsertWithoutCommitteeMemberInput
	connect?: Prisma.CommitteeWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.CommitteeUpdateToOneWithWhereWithoutCommitteeMemberInput, Prisma.CommitteeUpdateWithoutCommitteeMemberInput>,
		Prisma.CommitteeUncheckedUpdateWithoutCommitteeMemberInput
	>
}

export type CommitteeCreateNestedOneWithoutAcivityInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutAcivityInput, Prisma.CommitteeUncheckedCreateWithoutAcivityInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutAcivityInput
	connect?: Prisma.CommitteeWhereUniqueInput
}

export type CommitteeUpdateOneRequiredWithoutAcivityNestedInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutAcivityInput, Prisma.CommitteeUncheckedCreateWithoutAcivityInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutAcivityInput
	upsert?: Prisma.CommitteeUpsertWithoutAcivityInput
	connect?: Prisma.CommitteeWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.CommitteeUpdateToOneWithWhereWithoutAcivityInput, Prisma.CommitteeUpdateWithoutAcivityInput>,
		Prisma.CommitteeUncheckedUpdateWithoutAcivityInput
	>
}

export type CommitteeCreateNestedOneWithoutFinancialPersonDataCommitteeInput = {
	create?: Prisma.XOR<
		Prisma.CommitteeCreateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedCreateWithoutFinancialPersonDataCommitteeInput
	>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutFinancialPersonDataCommitteeInput
	connect?: Prisma.CommitteeWhereUniqueInput
}

export type CommitteeUpdateOneRequiredWithoutFinancialPersonDataCommitteeNestedInput = {
	create?: Prisma.XOR<
		Prisma.CommitteeCreateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedCreateWithoutFinancialPersonDataCommitteeInput
	>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutFinancialPersonDataCommitteeInput
	upsert?: Prisma.CommitteeUpsertWithoutFinancialPersonDataCommitteeInput
	connect?: Prisma.CommitteeWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.CommitteeUpdateToOneWithWhereWithoutFinancialPersonDataCommitteeInput,
			Prisma.CommitteeUpdateWithoutFinancialPersonDataCommitteeInput
		>,
		Prisma.CommitteeUncheckedUpdateWithoutFinancialPersonDataCommitteeInput
	>
}

export type CommitteeCreateNestedOneWithoutEmailAliasCommitteeInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedCreateWithoutEmailAliasCommitteeInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutEmailAliasCommitteeInput
	connect?: Prisma.CommitteeWhereUniqueInput
}

export type CommitteeUpdateOneRequiredWithoutEmailAliasCommitteeNestedInput = {
	create?: Prisma.XOR<Prisma.CommitteeCreateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedCreateWithoutEmailAliasCommitteeInput>
	connectOrCreate?: Prisma.CommitteeCreateOrConnectWithoutEmailAliasCommitteeInput
	upsert?: Prisma.CommitteeUpsertWithoutEmailAliasCommitteeInput
	connect?: Prisma.CommitteeWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.CommitteeUpdateToOneWithWhereWithoutEmailAliasCommitteeInput, Prisma.CommitteeUpdateWithoutEmailAliasCommitteeInput>,
		Prisma.CommitteeUncheckedUpdateWithoutEmailAliasCommitteeInput
	>
}

export type CommitteeCreateWithoutCommitteeMemberInput = {
	name: string
	ldapId: string
	isActive?: boolean
	Acivity?: Prisma.ActivityCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUncheckedCreateWithoutCommitteeMemberInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
	Acivity?: Prisma.ActivityUncheckedCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
}

export type CommitteeCreateOrConnectWithoutCommitteeMemberInput = {
	where: Prisma.CommitteeWhereUniqueInput
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedCreateWithoutCommitteeMemberInput>
}

export type CommitteeUpsertWithoutCommitteeMemberInput = {
	update: Prisma.XOR<Prisma.CommitteeUpdateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedUpdateWithoutCommitteeMemberInput>
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedCreateWithoutCommitteeMemberInput>
	where?: Prisma.CommitteeWhereInput
}

export type CommitteeUpdateToOneWithWhereWithoutCommitteeMemberInput = {
	where?: Prisma.CommitteeWhereInput
	data: Prisma.XOR<Prisma.CommitteeUpdateWithoutCommitteeMemberInput, Prisma.CommitteeUncheckedUpdateWithoutCommitteeMemberInput>
}

export type CommitteeUpdateWithoutCommitteeMemberInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	Acivity?: Prisma.ActivityUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeUncheckedUpdateWithoutCommitteeMemberInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	Acivity?: Prisma.ActivityUncheckedUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeCreateWithoutAcivityInput = {
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberCreateNestedManyWithoutCommitteeInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUncheckedCreateWithoutAcivityInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedCreateNestedManyWithoutCommitteeInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
}

export type CommitteeCreateOrConnectWithoutAcivityInput = {
	where: Prisma.CommitteeWhereUniqueInput
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutAcivityInput, Prisma.CommitteeUncheckedCreateWithoutAcivityInput>
}

export type CommitteeUpsertWithoutAcivityInput = {
	update: Prisma.XOR<Prisma.CommitteeUpdateWithoutAcivityInput, Prisma.CommitteeUncheckedUpdateWithoutAcivityInput>
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutAcivityInput, Prisma.CommitteeUncheckedCreateWithoutAcivityInput>
	where?: Prisma.CommitteeWhereInput
}

export type CommitteeUpdateToOneWithWhereWithoutAcivityInput = {
	where?: Prisma.CommitteeWhereInput
	data: Prisma.XOR<Prisma.CommitteeUpdateWithoutAcivityInput, Prisma.CommitteeUncheckedUpdateWithoutAcivityInput>
}

export type CommitteeUpdateWithoutAcivityInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUpdateManyWithoutCommitteeNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeUncheckedUpdateWithoutAcivityInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedUpdateManyWithoutCommitteeNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeCreateWithoutFinancialPersonDataCommitteeInput = {
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityCreateNestedManyWithoutOrganisedByInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUncheckedCreateWithoutFinancialPersonDataCommitteeInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityUncheckedCreateNestedManyWithoutOrganisedByInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
}

export type CommitteeCreateOrConnectWithoutFinancialPersonDataCommitteeInput = {
	where: Prisma.CommitteeWhereUniqueInput
	create: Prisma.XOR<
		Prisma.CommitteeCreateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedCreateWithoutFinancialPersonDataCommitteeInput
	>
}

export type CommitteeUpsertWithoutFinancialPersonDataCommitteeInput = {
	update: Prisma.XOR<
		Prisma.CommitteeUpdateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedUpdateWithoutFinancialPersonDataCommitteeInput
	>
	create: Prisma.XOR<
		Prisma.CommitteeCreateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedCreateWithoutFinancialPersonDataCommitteeInput
	>
	where?: Prisma.CommitteeWhereInput
}

export type CommitteeUpdateToOneWithWhereWithoutFinancialPersonDataCommitteeInput = {
	where?: Prisma.CommitteeWhereInput
	data: Prisma.XOR<
		Prisma.CommitteeUpdateWithoutFinancialPersonDataCommitteeInput,
		Prisma.CommitteeUncheckedUpdateWithoutFinancialPersonDataCommitteeInput
	>
}

export type CommitteeUpdateWithoutFinancialPersonDataCommitteeInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUpdateManyWithoutOrganisedByNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeUncheckedUpdateWithoutFinancialPersonDataCommitteeInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUncheckedUpdateManyWithoutOrganisedByNestedInput
	EmailAliasCommittee?: Prisma.EmailAliasCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeCreateWithoutEmailAliasCommitteeInput = {
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeCreateNestedManyWithoutCommitteeInput
}

export type CommitteeUncheckedCreateWithoutEmailAliasCommitteeInput = {
	id?: number
	name: string
	ldapId: string
	isActive?: boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedCreateNestedManyWithoutCommitteeInput
	Acivity?: Prisma.ActivityUncheckedCreateNestedManyWithoutOrganisedByInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedCreateNestedManyWithoutCommitteeInput
}

export type CommitteeCreateOrConnectWithoutEmailAliasCommitteeInput = {
	where: Prisma.CommitteeWhereUniqueInput
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedCreateWithoutEmailAliasCommitteeInput>
}

export type CommitteeUpsertWithoutEmailAliasCommitteeInput = {
	update: Prisma.XOR<Prisma.CommitteeUpdateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedUpdateWithoutEmailAliasCommitteeInput>
	create: Prisma.XOR<Prisma.CommitteeCreateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedCreateWithoutEmailAliasCommitteeInput>
	where?: Prisma.CommitteeWhereInput
}

export type CommitteeUpdateToOneWithWhereWithoutEmailAliasCommitteeInput = {
	where?: Prisma.CommitteeWhereInput
	data: Prisma.XOR<Prisma.CommitteeUpdateWithoutEmailAliasCommitteeInput, Prisma.CommitteeUncheckedUpdateWithoutEmailAliasCommitteeInput>
}

export type CommitteeUpdateWithoutEmailAliasCommitteeInput = {
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUpdateManyWithoutCommitteeNestedInput
}

export type CommitteeUncheckedUpdateWithoutEmailAliasCommitteeInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	name?: Prisma.StringFieldUpdateOperationsInput | string
	ldapId?: Prisma.StringFieldUpdateOperationsInput | string
	isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
	CommitteeMember?: Prisma.CommitteeMemberUncheckedUpdateManyWithoutCommitteeNestedInput
	Acivity?: Prisma.ActivityUncheckedUpdateManyWithoutOrganisedByNestedInput
	FinancialPersonDataCommittee?: Prisma.FinancialPersonDataCommitteeUncheckedUpdateManyWithoutCommitteeNestedInput
}

/**
 * Count Type CommitteeCountOutputType
 */

export type CommitteeCountOutputType = {
	CommitteeMember: number
	Acivity: number
	FinancialPersonDataCommittee: number
	EmailAliasCommittee: number
}

export type CommitteeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	CommitteeMember?: boolean | CommitteeCountOutputTypeCountCommitteeMemberArgs
	Acivity?: boolean | CommitteeCountOutputTypeCountAcivityArgs
	FinancialPersonDataCommittee?: boolean | CommitteeCountOutputTypeCountFinancialPersonDataCommitteeArgs
	EmailAliasCommittee?: boolean | CommitteeCountOutputTypeCountEmailAliasCommitteeArgs
}

/**
 * CommitteeCountOutputType without action
 */
export type CommitteeCountOutputTypeDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the CommitteeCountOutputType
	 */
	select?: Prisma.CommitteeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CommitteeCountOutputType without action
 */
export type CommitteeCountOutputTypeCountCommitteeMemberArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.CommitteeMemberWhereInput
}

/**
 * CommitteeCountOutputType without action
 */
export type CommitteeCountOutputTypeCountAcivityArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.ActivityWhereInput
}

/**
 * CommitteeCountOutputType without action
 */
export type CommitteeCountOutputTypeCountFinancialPersonDataCommitteeArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.FinancialPersonDataCommitteeWhereInput
}

/**
 * CommitteeCountOutputType without action
 */
export type CommitteeCountOutputTypeCountEmailAliasCommitteeArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.EmailAliasCommitteeWhereInput
}

export type CommitteeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetSelect<
		{
			id?: boolean
			name?: boolean
			ldapId?: boolean
			isActive?: boolean
			CommitteeMember?: boolean | Prisma.Committee$CommitteeMemberArgs<ExtArgs>
			Acivity?: boolean | Prisma.Committee$AcivityArgs<ExtArgs>
			FinancialPersonDataCommittee?: boolean | Prisma.Committee$FinancialPersonDataCommitteeArgs<ExtArgs>
			EmailAliasCommittee?: boolean | Prisma.Committee$EmailAliasCommitteeArgs<ExtArgs>
			_count?: boolean | Prisma.CommitteeCountOutputTypeDefaultArgs<ExtArgs>
		},
		ExtArgs['result']['committee']
	>

export type CommitteeSelectScalar = {
	id?: boolean
	name?: boolean
	ldapId?: boolean
	isActive?: boolean
}

export type CommitteeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetOmit<'id' | 'name' | 'ldapId' | 'isActive', ExtArgs['result']['committee']>
export type CommitteeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	CommitteeMember?: boolean | Prisma.Committee$CommitteeMemberArgs<ExtArgs>
	Acivity?: boolean | Prisma.Committee$AcivityArgs<ExtArgs>
	FinancialPersonDataCommittee?: boolean | Prisma.Committee$FinancialPersonDataCommitteeArgs<ExtArgs>
	EmailAliasCommittee?: boolean | Prisma.Committee$EmailAliasCommitteeArgs<ExtArgs>
	_count?: boolean | Prisma.CommitteeCountOutputTypeDefaultArgs<ExtArgs>
}

export type $CommitteePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	name: 'Committee'
	objects: {
		CommitteeMember: Prisma.$CommitteeMemberPayload<ExtArgs>[]
		Acivity: Prisma.$ActivityPayload<ExtArgs>[]
		FinancialPersonDataCommittee: Prisma.$FinancialPersonDataCommitteePayload<ExtArgs>[]
		EmailAliasCommittee: Prisma.$EmailAliasCommitteePayload<ExtArgs>[]
	}
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			id: number
			name: string
			ldapId: string
			isActive: boolean
		},
		ExtArgs['result']['committee']
	>
	composites: {}
}

export type CommitteeGetPayload<S extends boolean | null | undefined | CommitteeDefaultArgs> = runtime.Types.Result.GetResult<
	Prisma.$CommitteePayload,
	S
>

export type CommitteeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
	CommitteeFindManyArgs,
	'select' | 'include' | 'distinct' | 'omit'
> & {
	select?: CommitteeCountAggregateInputType | true
}

export interface CommitteeDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Committee']; meta: { name: 'Committee' } }
	/**
	 * Find zero or one Committee that matches the filter.
	 * @param {CommitteeFindUniqueArgs} args - Arguments to find a Committee
	 * @example
	 * // Get one Committee
	 * const committee = await prisma.committee.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends CommitteeFindUniqueArgs>(
		args: Prisma.SelectSubset<T, CommitteeFindUniqueArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find one Committee that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {CommitteeFindUniqueOrThrowArgs} args - Arguments to find a Committee
	 * @example
	 * // Get one Committee
	 * const committee = await prisma.committee.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends CommitteeFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, CommitteeFindUniqueOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first Committee that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeFindFirstArgs} args - Arguments to find a Committee
	 * @example
	 * // Get one Committee
	 * const committee = await prisma.committee.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends CommitteeFindFirstArgs>(
		args?: Prisma.SelectSubset<T, CommitteeFindFirstArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first Committee that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeFindFirstOrThrowArgs} args - Arguments to find a Committee
	 * @example
	 * // Get one Committee
	 * const committee = await prisma.committee.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends CommitteeFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, CommitteeFindFirstOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find zero or more Committees that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all Committees
	 * const committees = await prisma.committee.findMany()
	 *
	 * // Get first 10 Committees
	 * const committees = await prisma.committee.findMany({ take: 10 })
	 *
	 * // Only select the `id`
	 * const committeeWithIdOnly = await prisma.committee.findMany({ select: { id: true } })
	 *
	 */
	findMany<T extends CommitteeFindManyArgs>(
		args?: Prisma.SelectSubset<T, CommitteeFindManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>>

	/**
	 * Create a Committee.
	 * @param {CommitteeCreateArgs} args - Arguments to create a Committee.
	 * @example
	 * // Create one Committee
	 * const Committee = await prisma.committee.create({
	 *   data: {
	 *     // ... data to create a Committee
	 *   }
	 * })
	 *
	 */
	create<T extends CommitteeCreateArgs>(
		args: Prisma.SelectSubset<T, CommitteeCreateArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Create many Committees.
	 * @param {CommitteeCreateManyArgs} args - Arguments to create many Committees.
	 * @example
	 * // Create many Committees
	 * const committee = await prisma.committee.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends CommitteeCreateManyArgs>(
		args?: Prisma.SelectSubset<T, CommitteeCreateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Delete a Committee.
	 * @param {CommitteeDeleteArgs} args - Arguments to delete one Committee.
	 * @example
	 * // Delete one Committee
	 * const Committee = await prisma.committee.delete({
	 *   where: {
	 *     // ... filter to delete one Committee
	 *   }
	 * })
	 *
	 */
	delete<T extends CommitteeDeleteArgs>(
		args: Prisma.SelectSubset<T, CommitteeDeleteArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Update one Committee.
	 * @param {CommitteeUpdateArgs} args - Arguments to update one Committee.
	 * @example
	 * // Update one Committee
	 * const committee = await prisma.committee.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends CommitteeUpdateArgs>(
		args: Prisma.SelectSubset<T, CommitteeUpdateArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Delete zero or more Committees.
	 * @param {CommitteeDeleteManyArgs} args - Arguments to filter Committees to delete.
	 * @example
	 * // Delete a few Committees
	 * const { count } = await prisma.committee.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends CommitteeDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, CommitteeDeleteManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Update zero or more Committees.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many Committees
	 * const committee = await prisma.committee.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends CommitteeUpdateManyArgs>(
		args: Prisma.SelectSubset<T, CommitteeUpdateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Create or update one Committee.
	 * @param {CommitteeUpsertArgs} args - Arguments to update or create a Committee.
	 * @example
	 * // Update or create a Committee
	 * const committee = await prisma.committee.upsert({
	 *   create: {
	 *     // ... data to create a Committee
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the Committee we want to update
	 *   }
	 * })
	 */
	upsert<T extends CommitteeUpsertArgs>(
		args: Prisma.SelectSubset<T, CommitteeUpsertArgs<ExtArgs>>,
	): Prisma.Prisma__CommitteeClient<
		runtime.Types.Result.GetResult<Prisma.$CommitteePayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Count the number of Committees.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeCountArgs} args - Arguments to filter Committees to count.
	 * @example
	 * // Count the number of Committees
	 * const count = await prisma.committee.count({
	 *   where: {
	 *     // ... the filter for the Committees we want to count
	 *   }
	 * })
	 **/
	count<T extends CommitteeCountArgs>(
		args?: Prisma.Subset<T, CommitteeCountArgs>,
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<'select', any>
			? T['select'] extends true
				? number
				: Prisma.GetScalarType<T['select'], CommitteeCountAggregateOutputType>
			: number
	>

	/**
	 * Allows you to perform aggregations operations on a Committee.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends CommitteeAggregateArgs>(
		args: Prisma.Subset<T, CommitteeAggregateArgs>,
	): Prisma.PrismaPromise<GetCommitteeAggregateType<T>>

	/**
	 * Group by Committee.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {CommitteeGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends CommitteeGroupByArgs,
		HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: CommitteeGroupByArgs['orderBy'] }
			: { orderBy?: CommitteeGroupByArgs['orderBy'] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T['having']>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
					}[HavingFields]
				: 'take' extends Prisma.Keys<T>
					? 'orderBy' extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: 'skip' extends Prisma.Keys<T>
						? 'orderBy' extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields],
	>(
		args: Prisma.SubsetIntersection<T, CommitteeGroupByArgs, OrderByArg> & InputErrors,
	): {} extends InputErrors ? GetCommitteeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
	/**
	 * Fields of the Committee model
	 */
	readonly fields: CommitteeFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for Committee.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommitteeClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: 'PrismaPromise'
	CommitteeMember<T extends Prisma.Committee$CommitteeMemberArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Committee$CommitteeMemberArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommitteeMemberPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null>
	Acivity<T extends Prisma.Committee$AcivityArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Committee$AcivityArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null>
	FinancialPersonDataCommittee<T extends Prisma.Committee$FinancialPersonDataCommitteeArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Committee$FinancialPersonDataCommitteeArgs<ExtArgs>>,
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataCommitteePayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null
	>
	EmailAliasCommittee<T extends Prisma.Committee$EmailAliasCommitteeArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Committee$EmailAliasCommitteeArgs<ExtArgs>>,
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$EmailAliasCommitteePayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null
	>
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
	): runtime.Types.Utils.JsPromise<T | TResult>
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the Committee model
 */
export interface CommitteeFieldRefs {
	readonly id: Prisma.FieldRef<'Committee', 'Int'>
	readonly name: Prisma.FieldRef<'Committee', 'String'>
	readonly ldapId: Prisma.FieldRef<'Committee', 'String'>
	readonly isActive: Prisma.FieldRef<'Committee', 'Boolean'>
}

// Custom InputTypes
/**
 * Committee findUnique
 */
export type CommitteeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter, which Committee to fetch.
	 */
	where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee findUniqueOrThrow
 */
export type CommitteeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter, which Committee to fetch.
	 */
	where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee findFirst
 */
export type CommitteeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter, which Committee to fetch.
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Committees to fetch.
	 */
	orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for Committees.
	 */
	cursor?: Prisma.CommitteeWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Committees from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Committees.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of Committees.
	 */
	distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee findFirstOrThrow
 */
export type CommitteeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter, which Committee to fetch.
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Committees to fetch.
	 */
	orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for Committees.
	 */
	cursor?: Prisma.CommitteeWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Committees from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Committees.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of Committees.
	 */
	distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee findMany
 */
export type CommitteeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter, which Committees to fetch.
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Committees to fetch.
	 */
	orderBy?: Prisma.CommitteeOrderByWithRelationInput | Prisma.CommitteeOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing Committees.
	 */
	cursor?: Prisma.CommitteeWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Committees from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Committees.
	 */
	skip?: number
	distinct?: Prisma.CommitteeScalarFieldEnum | Prisma.CommitteeScalarFieldEnum[]
}

/**
 * Committee create
 */
export type CommitteeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * The data needed to create a Committee.
	 */
	data: Prisma.XOR<Prisma.CommitteeCreateInput, Prisma.CommitteeUncheckedCreateInput>
}

/**
 * Committee createMany
 */
export type CommitteeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to create many Committees.
	 */
	data: Prisma.CommitteeCreateManyInput | Prisma.CommitteeCreateManyInput[]
	skipDuplicates?: boolean
}

/**
 * Committee update
 */
export type CommitteeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * The data needed to update a Committee.
	 */
	data: Prisma.XOR<Prisma.CommitteeUpdateInput, Prisma.CommitteeUncheckedUpdateInput>
	/**
	 * Choose, which Committee to update.
	 */
	where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee updateMany
 */
export type CommitteeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to update Committees.
	 */
	data: Prisma.XOR<Prisma.CommitteeUpdateManyMutationInput, Prisma.CommitteeUncheckedUpdateManyInput>
	/**
	 * Filter which Committees to update
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * Limit how many Committees to update.
	 */
	limit?: number
}

/**
 * Committee upsert
 */
export type CommitteeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * The filter to search for the Committee to update in case it exists.
	 */
	where: Prisma.CommitteeWhereUniqueInput
	/**
	 * In case the Committee found by the `where` argument doesn't exist, create a new Committee with this data.
	 */
	create: Prisma.XOR<Prisma.CommitteeCreateInput, Prisma.CommitteeUncheckedCreateInput>
	/**
	 * In case the Committee was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.CommitteeUpdateInput, Prisma.CommitteeUncheckedUpdateInput>
}

/**
 * Committee delete
 */
export type CommitteeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
	/**
	 * Filter which Committee to delete.
	 */
	where: Prisma.CommitteeWhereUniqueInput
}

/**
 * Committee deleteMany
 */
export type CommitteeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which Committees to delete
	 */
	where?: Prisma.CommitteeWhereInput
	/**
	 * Limit how many Committees to delete.
	 */
	limit?: number
}

/**
 * Committee.CommitteeMember
 */
export type Committee$CommitteeMemberArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the CommitteeMember
	 */
	select?: Prisma.CommitteeMemberSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the CommitteeMember
	 */
	omit?: Prisma.CommitteeMemberOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeMemberInclude<ExtArgs> | null
	where?: Prisma.CommitteeMemberWhereInput
	orderBy?: Prisma.CommitteeMemberOrderByWithRelationInput | Prisma.CommitteeMemberOrderByWithRelationInput[]
	cursor?: Prisma.CommitteeMemberWhereUniqueInput
	take?: number
	skip?: number
	distinct?: Prisma.CommitteeMemberScalarFieldEnum | Prisma.CommitteeMemberScalarFieldEnum[]
}

/**
 * Committee.Acivity
 */
export type Committee$AcivityArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Activity
	 */
	select?: Prisma.ActivitySelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Activity
	 */
	omit?: Prisma.ActivityOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.ActivityInclude<ExtArgs> | null
	where?: Prisma.ActivityWhereInput
	orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
	cursor?: Prisma.ActivityWhereUniqueInput
	take?: number
	skip?: number
	distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Committee.FinancialPersonDataCommittee
 */
export type Committee$FinancialPersonDataCommitteeArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataCommittee
	 */
	select?: Prisma.FinancialPersonDataCommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataCommittee
	 */
	omit?: Prisma.FinancialPersonDataCommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataCommitteeInclude<ExtArgs> | null
	where?: Prisma.FinancialPersonDataCommitteeWhereInput
	orderBy?: Prisma.FinancialPersonDataCommitteeOrderByWithRelationInput | Prisma.FinancialPersonDataCommitteeOrderByWithRelationInput[]
	cursor?: Prisma.FinancialPersonDataCommitteeWhereUniqueInput
	take?: number
	skip?: number
	distinct?: Prisma.FinancialPersonDataCommitteeScalarFieldEnum | Prisma.FinancialPersonDataCommitteeScalarFieldEnum[]
}

/**
 * Committee.EmailAliasCommittee
 */
export type Committee$EmailAliasCommitteeArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the EmailAliasCommittee
	 */
	select?: Prisma.EmailAliasCommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the EmailAliasCommittee
	 */
	omit?: Prisma.EmailAliasCommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.EmailAliasCommitteeInclude<ExtArgs> | null
	where?: Prisma.EmailAliasCommitteeWhereInput
	orderBy?: Prisma.EmailAliasCommitteeOrderByWithRelationInput | Prisma.EmailAliasCommitteeOrderByWithRelationInput[]
	cursor?: Prisma.EmailAliasCommitteeWhereUniqueInput
	take?: number
	skip?: number
	distinct?: Prisma.EmailAliasCommitteeScalarFieldEnum | Prisma.EmailAliasCommitteeScalarFieldEnum[]
}

/**
 * Committee without action
 */
export type CommitteeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Committee
	 */
	select?: Prisma.CommitteeSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Committee
	 */
	omit?: Prisma.CommitteeOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.CommitteeInclude<ExtArgs> | null
}
