/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `DeclarationData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model DeclarationData
 *
 */
export type DeclarationDataModel = runtime.Types.Result.DefaultSelection<Prisma.$DeclarationDataPayload>

export type AggregateDeclarationData = {
	_count: DeclarationDataCountAggregateOutputType | null
	_avg: DeclarationDataAvgAggregateOutputType | null
	_sum: DeclarationDataSumAggregateOutputType | null
	_min: DeclarationDataMinAggregateOutputType | null
	_max: DeclarationDataMaxAggregateOutputType | null
}

export type DeclarationDataAvgAggregateOutputType = {
	id: number | null
	askedAmount: runtime.Decimal | null
	financialPersonId: number | null
	journalId: number | null
}

export type DeclarationDataSumAggregateOutputType = {
	id: number | null
	askedAmount: runtime.Decimal | null
	financialPersonId: number | null
	journalId: number | null
}

export type DeclarationDataMinAggregateOutputType = {
	id: number | null
	methodOfPayment: string | null
	receiveMethod: $Enums.ReceiveMethod | null
	status: $Enums.DeclarationStatus | null
	iban: string | null
	createdAt: Date | null
	updatedAt: Date | null
	askedAmount: runtime.Decimal | null
	reason: string | null
	financialPersonId: number | null
	journalId: number | null
}

export type DeclarationDataMaxAggregateOutputType = {
	id: number | null
	methodOfPayment: string | null
	receiveMethod: $Enums.ReceiveMethod | null
	status: $Enums.DeclarationStatus | null
	iban: string | null
	createdAt: Date | null
	updatedAt: Date | null
	askedAmount: runtime.Decimal | null
	reason: string | null
	financialPersonId: number | null
	journalId: number | null
}

export type DeclarationDataCountAggregateOutputType = {
	id: number
	methodOfPayment: number
	receiveMethod: number
	status: number
	iban: number
	createdAt: number
	updatedAt: number
	askedAmount: number
	reason: number
	financialPersonId: number
	journalId: number
	_all: number
}

export type DeclarationDataAvgAggregateInputType = {
	id?: true
	askedAmount?: true
	financialPersonId?: true
	journalId?: true
}

export type DeclarationDataSumAggregateInputType = {
	id?: true
	askedAmount?: true
	financialPersonId?: true
	journalId?: true
}

export type DeclarationDataMinAggregateInputType = {
	id?: true
	methodOfPayment?: true
	receiveMethod?: true
	status?: true
	iban?: true
	createdAt?: true
	updatedAt?: true
	askedAmount?: true
	reason?: true
	financialPersonId?: true
	journalId?: true
}

export type DeclarationDataMaxAggregateInputType = {
	id?: true
	methodOfPayment?: true
	receiveMethod?: true
	status?: true
	iban?: true
	createdAt?: true
	updatedAt?: true
	askedAmount?: true
	reason?: true
	financialPersonId?: true
	journalId?: true
}

export type DeclarationDataCountAggregateInputType = {
	id?: true
	methodOfPayment?: true
	receiveMethod?: true
	status?: true
	iban?: true
	createdAt?: true
	updatedAt?: true
	askedAmount?: true
	reason?: true
	financialPersonId?: true
	journalId?: true
	_all?: true
}

export type DeclarationDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which DeclarationData to aggregate.
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of DeclarationData to fetch.
	 */
	orderBy?: Prisma.DeclarationDataOrderByWithRelationInput | Prisma.DeclarationDataOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.DeclarationDataWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` DeclarationData from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` DeclarationData.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned DeclarationData
	 **/
	_count?: true | DeclarationDataCountAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: DeclarationDataAvgAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: DeclarationDataSumAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: DeclarationDataMinAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: DeclarationDataMaxAggregateInputType
}

export type GetDeclarationDataAggregateType<T extends DeclarationDataAggregateArgs> = {
	[P in keyof T & keyof AggregateDeclarationData]: P extends '_count' | 'count'
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateDeclarationData[P]>
		: Prisma.GetScalarType<T[P], AggregateDeclarationData[P]>
}

export type DeclarationDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	where?: Prisma.DeclarationDataWhereInput
	orderBy?: Prisma.DeclarationDataOrderByWithAggregationInput | Prisma.DeclarationDataOrderByWithAggregationInput[]
	by: Prisma.DeclarationDataScalarFieldEnum[] | Prisma.DeclarationDataScalarFieldEnum
	having?: Prisma.DeclarationDataScalarWhereWithAggregatesInput
	take?: number
	skip?: number
	_count?: DeclarationDataCountAggregateInputType | true
	_avg?: DeclarationDataAvgAggregateInputType
	_sum?: DeclarationDataSumAggregateInputType
	_min?: DeclarationDataMinAggregateInputType
	_max?: DeclarationDataMaxAggregateInputType
}

export type DeclarationDataGroupByOutputType = {
	id: number
	methodOfPayment: string
	receiveMethod: $Enums.ReceiveMethod
	status: $Enums.DeclarationStatus
	iban: string | null
	createdAt: Date
	updatedAt: Date
	askedAmount: runtime.Decimal
	reason: string
	financialPersonId: number
	journalId: number | null
	_count: DeclarationDataCountAggregateOutputType | null
	_avg: DeclarationDataAvgAggregateOutputType | null
	_sum: DeclarationDataSumAggregateOutputType | null
	_min: DeclarationDataMinAggregateOutputType | null
	_max: DeclarationDataMaxAggregateOutputType | null
}

type GetDeclarationDataGroupByPayload<T extends DeclarationDataGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<DeclarationDataGroupByOutputType, T['by']> & {
			[P in keyof T & keyof DeclarationDataGroupByOutputType]: P extends '_count'
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], DeclarationDataGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], DeclarationDataGroupByOutputType[P]>
		}
	>
>

export type DeclarationDataWhereInput = {
	AND?: Prisma.DeclarationDataWhereInput | Prisma.DeclarationDataWhereInput[]
	OR?: Prisma.DeclarationDataWhereInput[]
	NOT?: Prisma.DeclarationDataWhereInput | Prisma.DeclarationDataWhereInput[]
	id?: Prisma.IntFilter<'DeclarationData'> | number
	methodOfPayment?: Prisma.StringFilter<'DeclarationData'> | string
	receiveMethod?: Prisma.EnumReceiveMethodFilter<'DeclarationData'> | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFilter<'DeclarationData'> | $Enums.DeclarationStatus
	iban?: Prisma.StringNullableFilter<'DeclarationData'> | string | null
	createdAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
	updatedAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
	askedAmount?: Prisma.DecimalFilter<'DeclarationData'> | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFilter<'DeclarationData'> | string
	financialPersonId?: Prisma.IntFilter<'DeclarationData'> | number
	journalId?: Prisma.IntNullableFilter<'DeclarationData'> | number | null
	DeclaratedBy?: Prisma.XOR<Prisma.FinancialPersonScalarRelationFilter, Prisma.FinancialPersonWhereInput>
	Journal?: Prisma.XOR<Prisma.JournalNullableScalarRelationFilter, Prisma.JournalWhereInput> | null
}

export type DeclarationDataOrderByWithRelationInput = {
	id?: Prisma.SortOrder
	methodOfPayment?: Prisma.SortOrder
	receiveMethod?: Prisma.SortOrder
	status?: Prisma.SortOrder
	iban?: Prisma.SortOrderInput | Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	reason?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrderInput | Prisma.SortOrder
	DeclaratedBy?: Prisma.FinancialPersonOrderByWithRelationInput
	Journal?: Prisma.JournalOrderByWithRelationInput
	_relevance?: Prisma.DeclarationDataOrderByRelevanceInput
}

export type DeclarationDataWhereUniqueInput = Prisma.AtLeast<
	{
		id?: number
		journalId?: number
		AND?: Prisma.DeclarationDataWhereInput | Prisma.DeclarationDataWhereInput[]
		OR?: Prisma.DeclarationDataWhereInput[]
		NOT?: Prisma.DeclarationDataWhereInput | Prisma.DeclarationDataWhereInput[]
		methodOfPayment?: Prisma.StringFilter<'DeclarationData'> | string
		receiveMethod?: Prisma.EnumReceiveMethodFilter<'DeclarationData'> | $Enums.ReceiveMethod
		status?: Prisma.EnumDeclarationStatusFilter<'DeclarationData'> | $Enums.DeclarationStatus
		iban?: Prisma.StringNullableFilter<'DeclarationData'> | string | null
		createdAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
		updatedAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
		askedAmount?: Prisma.DecimalFilter<'DeclarationData'> | runtime.Decimal | runtime.DecimalJsLike | number | string
		reason?: Prisma.StringFilter<'DeclarationData'> | string
		financialPersonId?: Prisma.IntFilter<'DeclarationData'> | number
		DeclaratedBy?: Prisma.XOR<Prisma.FinancialPersonScalarRelationFilter, Prisma.FinancialPersonWhereInput>
		Journal?: Prisma.XOR<Prisma.JournalNullableScalarRelationFilter, Prisma.JournalWhereInput> | null
	},
	'id' | 'journalId'
>

export type DeclarationDataOrderByWithAggregationInput = {
	id?: Prisma.SortOrder
	methodOfPayment?: Prisma.SortOrder
	receiveMethod?: Prisma.SortOrder
	status?: Prisma.SortOrder
	iban?: Prisma.SortOrderInput | Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	reason?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrderInput | Prisma.SortOrder
	_count?: Prisma.DeclarationDataCountOrderByAggregateInput
	_avg?: Prisma.DeclarationDataAvgOrderByAggregateInput
	_max?: Prisma.DeclarationDataMaxOrderByAggregateInput
	_min?: Prisma.DeclarationDataMinOrderByAggregateInput
	_sum?: Prisma.DeclarationDataSumOrderByAggregateInput
}

export type DeclarationDataScalarWhereWithAggregatesInput = {
	AND?: Prisma.DeclarationDataScalarWhereWithAggregatesInput | Prisma.DeclarationDataScalarWhereWithAggregatesInput[]
	OR?: Prisma.DeclarationDataScalarWhereWithAggregatesInput[]
	NOT?: Prisma.DeclarationDataScalarWhereWithAggregatesInput | Prisma.DeclarationDataScalarWhereWithAggregatesInput[]
	id?: Prisma.IntWithAggregatesFilter<'DeclarationData'> | number
	methodOfPayment?: Prisma.StringWithAggregatesFilter<'DeclarationData'> | string
	receiveMethod?: Prisma.EnumReceiveMethodWithAggregatesFilter<'DeclarationData'> | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusWithAggregatesFilter<'DeclarationData'> | $Enums.DeclarationStatus
	iban?: Prisma.StringNullableWithAggregatesFilter<'DeclarationData'> | string | null
	createdAt?: Prisma.DateTimeWithAggregatesFilter<'DeclarationData'> | Date | string
	updatedAt?: Prisma.DateTimeWithAggregatesFilter<'DeclarationData'> | Date | string
	askedAmount?: Prisma.DecimalWithAggregatesFilter<'DeclarationData'> | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringWithAggregatesFilter<'DeclarationData'> | string
	financialPersonId?: Prisma.IntWithAggregatesFilter<'DeclarationData'> | number
	journalId?: Prisma.IntNullableWithAggregatesFilter<'DeclarationData'> | number | null
}

export type DeclarationDataCreateInput = {
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	DeclaratedBy: Prisma.FinancialPersonCreateNestedOneWithoutDeclarationDataInput
	Journal?: Prisma.JournalCreateNestedOneWithoutDeclarationDataInput
}

export type DeclarationDataUncheckedCreateInput = {
	id?: number
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	financialPersonId: number
	journalId?: number | null
}

export type DeclarationDataUpdateInput = {
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	DeclaratedBy?: Prisma.FinancialPersonUpdateOneRequiredWithoutDeclarationDataNestedInput
	Journal?: Prisma.JournalUpdateOneWithoutDeclarationDataNestedInput
}

export type DeclarationDataUncheckedUpdateInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	financialPersonId?: Prisma.IntFieldUpdateOperationsInput | number
	journalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type DeclarationDataCreateManyInput = {
	id?: number
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	financialPersonId: number
	journalId?: number | null
}

export type DeclarationDataUpdateManyMutationInput = {
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeclarationDataUncheckedUpdateManyInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	financialPersonId?: Prisma.IntFieldUpdateOperationsInput | number
	journalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type DeclarationDataListRelationFilter = {
	every?: Prisma.DeclarationDataWhereInput
	some?: Prisma.DeclarationDataWhereInput
	none?: Prisma.DeclarationDataWhereInput
}

export type DeclarationDataOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder
}

export type DeclarationDataNullableScalarRelationFilter = {
	is?: Prisma.DeclarationDataWhereInput | null
	isNot?: Prisma.DeclarationDataWhereInput | null
}

export type DeclarationDataOrderByRelevanceInput = {
	fields: Prisma.DeclarationDataOrderByRelevanceFieldEnum | Prisma.DeclarationDataOrderByRelevanceFieldEnum[]
	sort: Prisma.SortOrder
	search: string
}

export type DeclarationDataCountOrderByAggregateInput = {
	id?: Prisma.SortOrder
	methodOfPayment?: Prisma.SortOrder
	receiveMethod?: Prisma.SortOrder
	status?: Prisma.SortOrder
	iban?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	reason?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrder
}

export type DeclarationDataAvgOrderByAggregateInput = {
	id?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrder
}

export type DeclarationDataMaxOrderByAggregateInput = {
	id?: Prisma.SortOrder
	methodOfPayment?: Prisma.SortOrder
	receiveMethod?: Prisma.SortOrder
	status?: Prisma.SortOrder
	iban?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	reason?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrder
}

export type DeclarationDataMinOrderByAggregateInput = {
	id?: Prisma.SortOrder
	methodOfPayment?: Prisma.SortOrder
	receiveMethod?: Prisma.SortOrder
	status?: Prisma.SortOrder
	iban?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	reason?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrder
}

export type DeclarationDataSumOrderByAggregateInput = {
	id?: Prisma.SortOrder
	askedAmount?: Prisma.SortOrder
	financialPersonId?: Prisma.SortOrder
	journalId?: Prisma.SortOrder
}

export type DeclarationDataCreateNestedManyWithoutDeclaratedByInput = {
	create?:
		| Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
		| Prisma.DeclarationDataCreateWithoutDeclaratedByInput[]
		| Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput[]
	connectOrCreate?:
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput[]
	createMany?: Prisma.DeclarationDataCreateManyDeclaratedByInputEnvelope
	connect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
}

export type DeclarationDataUncheckedCreateNestedManyWithoutDeclaratedByInput = {
	create?:
		| Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
		| Prisma.DeclarationDataCreateWithoutDeclaratedByInput[]
		| Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput[]
	connectOrCreate?:
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput[]
	createMany?: Prisma.DeclarationDataCreateManyDeclaratedByInputEnvelope
	connect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
}

export type DeclarationDataUpdateManyWithoutDeclaratedByNestedInput = {
	create?:
		| Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
		| Prisma.DeclarationDataCreateWithoutDeclaratedByInput[]
		| Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput[]
	connectOrCreate?:
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput[]
	upsert?:
		| Prisma.DeclarationDataUpsertWithWhereUniqueWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpsertWithWhereUniqueWithoutDeclaratedByInput[]
	createMany?: Prisma.DeclarationDataCreateManyDeclaratedByInputEnvelope
	set?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	disconnect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	delete?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	connect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	update?:
		| Prisma.DeclarationDataUpdateWithWhereUniqueWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpdateWithWhereUniqueWithoutDeclaratedByInput[]
	updateMany?:
		| Prisma.DeclarationDataUpdateManyWithWhereWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpdateManyWithWhereWithoutDeclaratedByInput[]
	deleteMany?: Prisma.DeclarationDataScalarWhereInput | Prisma.DeclarationDataScalarWhereInput[]
}

export type DeclarationDataUncheckedUpdateManyWithoutDeclaratedByNestedInput = {
	create?:
		| Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
		| Prisma.DeclarationDataCreateWithoutDeclaratedByInput[]
		| Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput[]
	connectOrCreate?:
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput
		| Prisma.DeclarationDataCreateOrConnectWithoutDeclaratedByInput[]
	upsert?:
		| Prisma.DeclarationDataUpsertWithWhereUniqueWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpsertWithWhereUniqueWithoutDeclaratedByInput[]
	createMany?: Prisma.DeclarationDataCreateManyDeclaratedByInputEnvelope
	set?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	disconnect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	delete?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	connect?: Prisma.DeclarationDataWhereUniqueInput | Prisma.DeclarationDataWhereUniqueInput[]
	update?:
		| Prisma.DeclarationDataUpdateWithWhereUniqueWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpdateWithWhereUniqueWithoutDeclaratedByInput[]
	updateMany?:
		| Prisma.DeclarationDataUpdateManyWithWhereWithoutDeclaratedByInput
		| Prisma.DeclarationDataUpdateManyWithWhereWithoutDeclaratedByInput[]
	deleteMany?: Prisma.DeclarationDataScalarWhereInput | Prisma.DeclarationDataScalarWhereInput[]
}

export type DeclarationDataCreateNestedOneWithoutJournalInput = {
	create?: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
	connectOrCreate?: Prisma.DeclarationDataCreateOrConnectWithoutJournalInput
	connect?: Prisma.DeclarationDataWhereUniqueInput
}

export type DeclarationDataUncheckedCreateNestedOneWithoutJournalInput = {
	create?: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
	connectOrCreate?: Prisma.DeclarationDataCreateOrConnectWithoutJournalInput
	connect?: Prisma.DeclarationDataWhereUniqueInput
}

export type DeclarationDataUpdateOneWithoutJournalNestedInput = {
	create?: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
	connectOrCreate?: Prisma.DeclarationDataCreateOrConnectWithoutJournalInput
	upsert?: Prisma.DeclarationDataUpsertWithoutJournalInput
	disconnect?: Prisma.DeclarationDataWhereInput | boolean
	delete?: Prisma.DeclarationDataWhereInput | boolean
	connect?: Prisma.DeclarationDataWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.DeclarationDataUpdateToOneWithWhereWithoutJournalInput, Prisma.DeclarationDataUpdateWithoutJournalInput>,
		Prisma.DeclarationDataUncheckedUpdateWithoutJournalInput
	>
}

export type DeclarationDataUncheckedUpdateOneWithoutJournalNestedInput = {
	create?: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
	connectOrCreate?: Prisma.DeclarationDataCreateOrConnectWithoutJournalInput
	upsert?: Prisma.DeclarationDataUpsertWithoutJournalInput
	disconnect?: Prisma.DeclarationDataWhereInput | boolean
	delete?: Prisma.DeclarationDataWhereInput | boolean
	connect?: Prisma.DeclarationDataWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.DeclarationDataUpdateToOneWithWhereWithoutJournalInput, Prisma.DeclarationDataUpdateWithoutJournalInput>,
		Prisma.DeclarationDataUncheckedUpdateWithoutJournalInput
	>
}

export type EnumReceiveMethodFieldUpdateOperationsInput = {
	set?: $Enums.ReceiveMethod
}

export type EnumDeclarationStatusFieldUpdateOperationsInput = {
	set?: $Enums.DeclarationStatus
}

export type DeclarationDataCreateWithoutDeclaratedByInput = {
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	Journal?: Prisma.JournalCreateNestedOneWithoutDeclarationDataInput
}

export type DeclarationDataUncheckedCreateWithoutDeclaratedByInput = {
	id?: number
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	journalId?: number | null
}

export type DeclarationDataCreateOrConnectWithoutDeclaratedByInput = {
	where: Prisma.DeclarationDataWhereUniqueInput
	create: Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
}

export type DeclarationDataCreateManyDeclaratedByInputEnvelope = {
	data: Prisma.DeclarationDataCreateManyDeclaratedByInput | Prisma.DeclarationDataCreateManyDeclaratedByInput[]
	skipDuplicates?: boolean
}

export type DeclarationDataUpsertWithWhereUniqueWithoutDeclaratedByInput = {
	where: Prisma.DeclarationDataWhereUniqueInput
	update: Prisma.XOR<Prisma.DeclarationDataUpdateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedUpdateWithoutDeclaratedByInput>
	create: Prisma.XOR<Prisma.DeclarationDataCreateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedCreateWithoutDeclaratedByInput>
}

export type DeclarationDataUpdateWithWhereUniqueWithoutDeclaratedByInput = {
	where: Prisma.DeclarationDataWhereUniqueInput
	data: Prisma.XOR<Prisma.DeclarationDataUpdateWithoutDeclaratedByInput, Prisma.DeclarationDataUncheckedUpdateWithoutDeclaratedByInput>
}

export type DeclarationDataUpdateManyWithWhereWithoutDeclaratedByInput = {
	where: Prisma.DeclarationDataScalarWhereInput
	data: Prisma.XOR<Prisma.DeclarationDataUpdateManyMutationInput, Prisma.DeclarationDataUncheckedUpdateManyWithoutDeclaratedByInput>
}

export type DeclarationDataScalarWhereInput = {
	AND?: Prisma.DeclarationDataScalarWhereInput | Prisma.DeclarationDataScalarWhereInput[]
	OR?: Prisma.DeclarationDataScalarWhereInput[]
	NOT?: Prisma.DeclarationDataScalarWhereInput | Prisma.DeclarationDataScalarWhereInput[]
	id?: Prisma.IntFilter<'DeclarationData'> | number
	methodOfPayment?: Prisma.StringFilter<'DeclarationData'> | string
	receiveMethod?: Prisma.EnumReceiveMethodFilter<'DeclarationData'> | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFilter<'DeclarationData'> | $Enums.DeclarationStatus
	iban?: Prisma.StringNullableFilter<'DeclarationData'> | string | null
	createdAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
	updatedAt?: Prisma.DateTimeFilter<'DeclarationData'> | Date | string
	askedAmount?: Prisma.DecimalFilter<'DeclarationData'> | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFilter<'DeclarationData'> | string
	financialPersonId?: Prisma.IntFilter<'DeclarationData'> | number
	journalId?: Prisma.IntNullableFilter<'DeclarationData'> | number | null
}

export type DeclarationDataCreateWithoutJournalInput = {
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	DeclaratedBy: Prisma.FinancialPersonCreateNestedOneWithoutDeclarationDataInput
}

export type DeclarationDataUncheckedCreateWithoutJournalInput = {
	id?: number
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	financialPersonId: number
}

export type DeclarationDataCreateOrConnectWithoutJournalInput = {
	where: Prisma.DeclarationDataWhereUniqueInput
	create: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
}

export type DeclarationDataUpsertWithoutJournalInput = {
	update: Prisma.XOR<Prisma.DeclarationDataUpdateWithoutJournalInput, Prisma.DeclarationDataUncheckedUpdateWithoutJournalInput>
	create: Prisma.XOR<Prisma.DeclarationDataCreateWithoutJournalInput, Prisma.DeclarationDataUncheckedCreateWithoutJournalInput>
	where?: Prisma.DeclarationDataWhereInput
}

export type DeclarationDataUpdateToOneWithWhereWithoutJournalInput = {
	where?: Prisma.DeclarationDataWhereInput
	data: Prisma.XOR<Prisma.DeclarationDataUpdateWithoutJournalInput, Prisma.DeclarationDataUncheckedUpdateWithoutJournalInput>
}

export type DeclarationDataUpdateWithoutJournalInput = {
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	DeclaratedBy?: Prisma.FinancialPersonUpdateOneRequiredWithoutDeclarationDataNestedInput
}

export type DeclarationDataUncheckedUpdateWithoutJournalInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	financialPersonId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DeclarationDataCreateManyDeclaratedByInput = {
	id?: number
	methodOfPayment?: string
	receiveMethod?: $Enums.ReceiveMethod
	status?: $Enums.DeclarationStatus
	iban?: string | null
	createdAt?: Date | string
	updatedAt?: Date | string
	askedAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
	reason: string
	journalId?: number | null
}

export type DeclarationDataUpdateWithoutDeclaratedByInput = {
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	Journal?: Prisma.JournalUpdateOneWithoutDeclarationDataNestedInput
}

export type DeclarationDataUncheckedUpdateWithoutDeclaratedByInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	journalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type DeclarationDataUncheckedUpdateManyWithoutDeclaratedByInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	methodOfPayment?: Prisma.StringFieldUpdateOperationsInput | string
	receiveMethod?: Prisma.EnumReceiveMethodFieldUpdateOperationsInput | $Enums.ReceiveMethod
	status?: Prisma.EnumDeclarationStatusFieldUpdateOperationsInput | $Enums.DeclarationStatus
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	askedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
	reason?: Prisma.StringFieldUpdateOperationsInput | string
	journalId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type DeclarationDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetSelect<
		{
			id?: boolean
			methodOfPayment?: boolean
			receiveMethod?: boolean
			status?: boolean
			iban?: boolean
			createdAt?: boolean
			updatedAt?: boolean
			askedAmount?: boolean
			reason?: boolean
			financialPersonId?: boolean
			journalId?: boolean
			DeclaratedBy?: boolean | Prisma.FinancialPersonDefaultArgs<ExtArgs>
			Journal?: boolean | Prisma.DeclarationData$JournalArgs<ExtArgs>
		},
		ExtArgs['result']['declarationData']
	>

export type DeclarationDataSelectScalar = {
	id?: boolean
	methodOfPayment?: boolean
	receiveMethod?: boolean
	status?: boolean
	iban?: boolean
	createdAt?: boolean
	updatedAt?: boolean
	askedAmount?: boolean
	reason?: boolean
	financialPersonId?: boolean
	journalId?: boolean
}

export type DeclarationDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetOmit<
		| 'id'
		| 'methodOfPayment'
		| 'receiveMethod'
		| 'status'
		| 'iban'
		| 'createdAt'
		| 'updatedAt'
		| 'askedAmount'
		| 'reason'
		| 'financialPersonId'
		| 'journalId',
		ExtArgs['result']['declarationData']
	>
export type DeclarationDataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	DeclaratedBy?: boolean | Prisma.FinancialPersonDefaultArgs<ExtArgs>
	Journal?: boolean | Prisma.DeclarationData$JournalArgs<ExtArgs>
}

export type $DeclarationDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	name: 'DeclarationData'
	objects: {
		DeclaratedBy: Prisma.$FinancialPersonPayload<ExtArgs>
		Journal: Prisma.$JournalPayload<ExtArgs> | null
	}
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			id: number
			methodOfPayment: string
			receiveMethod: $Enums.ReceiveMethod
			status: $Enums.DeclarationStatus
			iban: string | null
			createdAt: Date
			updatedAt: Date
			askedAmount: runtime.Decimal
			reason: string
			financialPersonId: number
			journalId: number | null
		},
		ExtArgs['result']['declarationData']
	>
	composites: {}
}

export type DeclarationDataGetPayload<S extends boolean | null | undefined | DeclarationDataDefaultArgs> = runtime.Types.Result.GetResult<
	Prisma.$DeclarationDataPayload,
	S
>

export type DeclarationDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
	DeclarationDataFindManyArgs,
	'select' | 'include' | 'distinct' | 'omit'
> & {
	select?: DeclarationDataCountAggregateInputType | true
}

export interface DeclarationDataDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DeclarationData']; meta: { name: 'DeclarationData' } }
	/**
	 * Find zero or one DeclarationData that matches the filter.
	 * @param {DeclarationDataFindUniqueArgs} args - Arguments to find a DeclarationData
	 * @example
	 * // Get one DeclarationData
	 * const declarationData = await prisma.declarationData.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends DeclarationDataFindUniqueArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataFindUniqueArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find one DeclarationData that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {DeclarationDataFindUniqueOrThrowArgs} args - Arguments to find a DeclarationData
	 * @example
	 * // Get one DeclarationData
	 * const declarationData = await prisma.declarationData.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends DeclarationDataFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataFindUniqueOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first DeclarationData that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataFindFirstArgs} args - Arguments to find a DeclarationData
	 * @example
	 * // Get one DeclarationData
	 * const declarationData = await prisma.declarationData.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends DeclarationDataFindFirstArgs>(
		args?: Prisma.SelectSubset<T, DeclarationDataFindFirstArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first DeclarationData that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataFindFirstOrThrowArgs} args - Arguments to find a DeclarationData
	 * @example
	 * // Get one DeclarationData
	 * const declarationData = await prisma.declarationData.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends DeclarationDataFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, DeclarationDataFindFirstOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find zero or more DeclarationData that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all DeclarationData
	 * const declarationData = await prisma.declarationData.findMany()
	 *
	 * // Get first 10 DeclarationData
	 * const declarationData = await prisma.declarationData.findMany({ take: 10 })
	 *
	 * // Only select the `id`
	 * const declarationDataWithIdOnly = await prisma.declarationData.findMany({ select: { id: true } })
	 *
	 */
	findMany<T extends DeclarationDataFindManyArgs>(
		args?: Prisma.SelectSubset<T, DeclarationDataFindManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>>

	/**
	 * Create a DeclarationData.
	 * @param {DeclarationDataCreateArgs} args - Arguments to create a DeclarationData.
	 * @example
	 * // Create one DeclarationData
	 * const DeclarationData = await prisma.declarationData.create({
	 *   data: {
	 *     // ... data to create a DeclarationData
	 *   }
	 * })
	 *
	 */
	create<T extends DeclarationDataCreateArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataCreateArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Create many DeclarationData.
	 * @param {DeclarationDataCreateManyArgs} args - Arguments to create many DeclarationData.
	 * @example
	 * // Create many DeclarationData
	 * const declarationData = await prisma.declarationData.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends DeclarationDataCreateManyArgs>(
		args?: Prisma.SelectSubset<T, DeclarationDataCreateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Delete a DeclarationData.
	 * @param {DeclarationDataDeleteArgs} args - Arguments to delete one DeclarationData.
	 * @example
	 * // Delete one DeclarationData
	 * const DeclarationData = await prisma.declarationData.delete({
	 *   where: {
	 *     // ... filter to delete one DeclarationData
	 *   }
	 * })
	 *
	 */
	delete<T extends DeclarationDataDeleteArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataDeleteArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Update one DeclarationData.
	 * @param {DeclarationDataUpdateArgs} args - Arguments to update one DeclarationData.
	 * @example
	 * // Update one DeclarationData
	 * const declarationData = await prisma.declarationData.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends DeclarationDataUpdateArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataUpdateArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Delete zero or more DeclarationData.
	 * @param {DeclarationDataDeleteManyArgs} args - Arguments to filter DeclarationData to delete.
	 * @example
	 * // Delete a few DeclarationData
	 * const { count } = await prisma.declarationData.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends DeclarationDataDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, DeclarationDataDeleteManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Update zero or more DeclarationData.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many DeclarationData
	 * const declarationData = await prisma.declarationData.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends DeclarationDataUpdateManyArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataUpdateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Create or update one DeclarationData.
	 * @param {DeclarationDataUpsertArgs} args - Arguments to update or create a DeclarationData.
	 * @example
	 * // Update or create a DeclarationData
	 * const declarationData = await prisma.declarationData.upsert({
	 *   create: {
	 *     // ... data to create a DeclarationData
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the DeclarationData we want to update
	 *   }
	 * })
	 */
	upsert<T extends DeclarationDataUpsertArgs>(
		args: Prisma.SelectSubset<T, DeclarationDataUpsertArgs<ExtArgs>>,
	): Prisma.Prisma__DeclarationDataClient<
		runtime.Types.Result.GetResult<Prisma.$DeclarationDataPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Count the number of DeclarationData.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataCountArgs} args - Arguments to filter DeclarationData to count.
	 * @example
	 * // Count the number of DeclarationData
	 * const count = await prisma.declarationData.count({
	 *   where: {
	 *     // ... the filter for the DeclarationData we want to count
	 *   }
	 * })
	 **/
	count<T extends DeclarationDataCountArgs>(
		args?: Prisma.Subset<T, DeclarationDataCountArgs>,
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<'select', any>
			? T['select'] extends true
				? number
				: Prisma.GetScalarType<T['select'], DeclarationDataCountAggregateOutputType>
			: number
	>

	/**
	 * Allows you to perform aggregations operations on a DeclarationData.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends DeclarationDataAggregateArgs>(
		args: Prisma.Subset<T, DeclarationDataAggregateArgs>,
	): Prisma.PrismaPromise<GetDeclarationDataAggregateType<T>>

	/**
	 * Group by DeclarationData.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {DeclarationDataGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends DeclarationDataGroupByArgs,
		HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: DeclarationDataGroupByArgs['orderBy'] }
			: { orderBy?: DeclarationDataGroupByArgs['orderBy'] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T['having']>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
					}[HavingFields]
				: 'take' extends Prisma.Keys<T>
					? 'orderBy' extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: 'skip' extends Prisma.Keys<T>
						? 'orderBy' extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields],
	>(
		args: Prisma.SubsetIntersection<T, DeclarationDataGroupByArgs, OrderByArg> & InputErrors,
	): {} extends InputErrors ? GetDeclarationDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
	/**
	 * Fields of the DeclarationData model
	 */
	readonly fields: DeclarationDataFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for DeclarationData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeclarationDataClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: 'PrismaPromise'
	DeclaratedBy<T extends Prisma.FinancialPersonDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.FinancialPersonDefaultArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>
	Journal<T extends Prisma.DeclarationData$JournalArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.DeclarationData$JournalArgs<ExtArgs>>,
	): Prisma.Prisma__JournalClient<
		runtime.Types.Result.GetResult<Prisma.$JournalPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
	): runtime.Types.Utils.JsPromise<T | TResult>
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the DeclarationData model
 */
export interface DeclarationDataFieldRefs {
	readonly id: Prisma.FieldRef<'DeclarationData', 'Int'>
	readonly methodOfPayment: Prisma.FieldRef<'DeclarationData', 'String'>
	readonly receiveMethod: Prisma.FieldRef<'DeclarationData', 'ReceiveMethod'>
	readonly status: Prisma.FieldRef<'DeclarationData', 'DeclarationStatus'>
	readonly iban: Prisma.FieldRef<'DeclarationData', 'String'>
	readonly createdAt: Prisma.FieldRef<'DeclarationData', 'DateTime'>
	readonly updatedAt: Prisma.FieldRef<'DeclarationData', 'DateTime'>
	readonly askedAmount: Prisma.FieldRef<'DeclarationData', 'Decimal'>
	readonly reason: Prisma.FieldRef<'DeclarationData', 'String'>
	readonly financialPersonId: Prisma.FieldRef<'DeclarationData', 'Int'>
	readonly journalId: Prisma.FieldRef<'DeclarationData', 'Int'>
}

// Custom InputTypes
/**
 * DeclarationData findUnique
 */
export type DeclarationDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter, which DeclarationData to fetch.
	 */
	where: Prisma.DeclarationDataWhereUniqueInput
}

/**
 * DeclarationData findUniqueOrThrow
 */
export type DeclarationDataFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter, which DeclarationData to fetch.
	 */
	where: Prisma.DeclarationDataWhereUniqueInput
}

/**
 * DeclarationData findFirst
 */
export type DeclarationDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter, which DeclarationData to fetch.
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of DeclarationData to fetch.
	 */
	orderBy?: Prisma.DeclarationDataOrderByWithRelationInput | Prisma.DeclarationDataOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for DeclarationData.
	 */
	cursor?: Prisma.DeclarationDataWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` DeclarationData from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` DeclarationData.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of DeclarationData.
	 */
	distinct?: Prisma.DeclarationDataScalarFieldEnum | Prisma.DeclarationDataScalarFieldEnum[]
}

/**
 * DeclarationData findFirstOrThrow
 */
export type DeclarationDataFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter, which DeclarationData to fetch.
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of DeclarationData to fetch.
	 */
	orderBy?: Prisma.DeclarationDataOrderByWithRelationInput | Prisma.DeclarationDataOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for DeclarationData.
	 */
	cursor?: Prisma.DeclarationDataWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` DeclarationData from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` DeclarationData.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of DeclarationData.
	 */
	distinct?: Prisma.DeclarationDataScalarFieldEnum | Prisma.DeclarationDataScalarFieldEnum[]
}

/**
 * DeclarationData findMany
 */
export type DeclarationDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter, which DeclarationData to fetch.
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of DeclarationData to fetch.
	 */
	orderBy?: Prisma.DeclarationDataOrderByWithRelationInput | Prisma.DeclarationDataOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing DeclarationData.
	 */
	cursor?: Prisma.DeclarationDataWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` DeclarationData from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` DeclarationData.
	 */
	skip?: number
	distinct?: Prisma.DeclarationDataScalarFieldEnum | Prisma.DeclarationDataScalarFieldEnum[]
}

/**
 * DeclarationData create
 */
export type DeclarationDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * The data needed to create a DeclarationData.
	 */
	data: Prisma.XOR<Prisma.DeclarationDataCreateInput, Prisma.DeclarationDataUncheckedCreateInput>
}

/**
 * DeclarationData createMany
 */
export type DeclarationDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to create many DeclarationData.
	 */
	data: Prisma.DeclarationDataCreateManyInput | Prisma.DeclarationDataCreateManyInput[]
	skipDuplicates?: boolean
}

/**
 * DeclarationData update
 */
export type DeclarationDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * The data needed to update a DeclarationData.
	 */
	data: Prisma.XOR<Prisma.DeclarationDataUpdateInput, Prisma.DeclarationDataUncheckedUpdateInput>
	/**
	 * Choose, which DeclarationData to update.
	 */
	where: Prisma.DeclarationDataWhereUniqueInput
}

/**
 * DeclarationData updateMany
 */
export type DeclarationDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to update DeclarationData.
	 */
	data: Prisma.XOR<Prisma.DeclarationDataUpdateManyMutationInput, Prisma.DeclarationDataUncheckedUpdateManyInput>
	/**
	 * Filter which DeclarationData to update
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * Limit how many DeclarationData to update.
	 */
	limit?: number
}

/**
 * DeclarationData upsert
 */
export type DeclarationDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * The filter to search for the DeclarationData to update in case it exists.
	 */
	where: Prisma.DeclarationDataWhereUniqueInput
	/**
	 * In case the DeclarationData found by the `where` argument doesn't exist, create a new DeclarationData with this data.
	 */
	create: Prisma.XOR<Prisma.DeclarationDataCreateInput, Prisma.DeclarationDataUncheckedCreateInput>
	/**
	 * In case the DeclarationData was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.DeclarationDataUpdateInput, Prisma.DeclarationDataUncheckedUpdateInput>
}

/**
 * DeclarationData delete
 */
export type DeclarationDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
	/**
	 * Filter which DeclarationData to delete.
	 */
	where: Prisma.DeclarationDataWhereUniqueInput
}

/**
 * DeclarationData deleteMany
 */
export type DeclarationDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which DeclarationData to delete
	 */
	where?: Prisma.DeclarationDataWhereInput
	/**
	 * Limit how many DeclarationData to delete.
	 */
	limit?: number
}

/**
 * DeclarationData.Journal
 */
export type DeclarationData$JournalArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Journal
	 */
	select?: Prisma.JournalSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Journal
	 */
	omit?: Prisma.JournalOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.JournalInclude<ExtArgs> | null
	where?: Prisma.JournalWhereInput
}

/**
 * DeclarationData without action
 */
export type DeclarationDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the DeclarationData
	 */
	select?: Prisma.DeclarationDataSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the DeclarationData
	 */
	omit?: Prisma.DeclarationDataOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.DeclarationDataInclude<ExtArgs> | null
}
