/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `FinancialPersonDataOther` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model FinancialPersonDataOther
 *
 */
export type FinancialPersonDataOtherModel = runtime.Types.Result.DefaultSelection<Prisma.$FinancialPersonDataOtherPayload>

export type AggregateFinancialPersonDataOther = {
	_count: FinancialPersonDataOtherCountAggregateOutputType | null
	_avg: FinancialPersonDataOtherAvgAggregateOutputType | null
	_sum: FinancialPersonDataOtherSumAggregateOutputType | null
	_min: FinancialPersonDataOtherMinAggregateOutputType | null
	_max: FinancialPersonDataOtherMaxAggregateOutputType | null
}

export type FinancialPersonDataOtherAvgAggregateOutputType = {
	personId: number | null
}

export type FinancialPersonDataOtherSumAggregateOutputType = {
	personId: number | null
}

export type FinancialPersonDataOtherMinAggregateOutputType = {
	personId: number | null
	description: string | null
	email: string | null
	address: string | null
	postalCode: string | null
	city: string | null
	iban: string | null
}

export type FinancialPersonDataOtherMaxAggregateOutputType = {
	personId: number | null
	description: string | null
	email: string | null
	address: string | null
	postalCode: string | null
	city: string | null
	iban: string | null
}

export type FinancialPersonDataOtherCountAggregateOutputType = {
	personId: number
	description: number
	email: number
	address: number
	postalCode: number
	city: number
	iban: number
	_all: number
}

export type FinancialPersonDataOtherAvgAggregateInputType = {
	personId?: true
}

export type FinancialPersonDataOtherSumAggregateInputType = {
	personId?: true
}

export type FinancialPersonDataOtherMinAggregateInputType = {
	personId?: true
	description?: true
	email?: true
	address?: true
	postalCode?: true
	city?: true
	iban?: true
}

export type FinancialPersonDataOtherMaxAggregateInputType = {
	personId?: true
	description?: true
	email?: true
	address?: true
	postalCode?: true
	city?: true
	iban?: true
}

export type FinancialPersonDataOtherCountAggregateInputType = {
	personId?: true
	description?: true
	email?: true
	address?: true
	postalCode?: true
	city?: true
	iban?: true
	_all?: true
}

export type FinancialPersonDataOtherAggregateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Filter which FinancialPersonDataOther to aggregate.
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of FinancialPersonDataOthers to fetch.
	 */
	orderBy?: Prisma.FinancialPersonDataOtherOrderByWithRelationInput | Prisma.FinancialPersonDataOtherOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` FinancialPersonDataOthers from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` FinancialPersonDataOthers.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned FinancialPersonDataOthers
	 **/
	_count?: true | FinancialPersonDataOtherCountAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: FinancialPersonDataOtherAvgAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: FinancialPersonDataOtherSumAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: FinancialPersonDataOtherMinAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: FinancialPersonDataOtherMaxAggregateInputType
}

export type GetFinancialPersonDataOtherAggregateType<T extends FinancialPersonDataOtherAggregateArgs> = {
	[P in keyof T & keyof AggregateFinancialPersonDataOther]: P extends '_count' | 'count'
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateFinancialPersonDataOther[P]>
		: Prisma.GetScalarType<T[P], AggregateFinancialPersonDataOther[P]>
}

export type FinancialPersonDataOtherGroupByArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.FinancialPersonDataOtherWhereInput
	orderBy?: Prisma.FinancialPersonDataOtherOrderByWithAggregationInput | Prisma.FinancialPersonDataOtherOrderByWithAggregationInput[]
	by: Prisma.FinancialPersonDataOtherScalarFieldEnum[] | Prisma.FinancialPersonDataOtherScalarFieldEnum
	having?: Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput
	take?: number
	skip?: number
	_count?: FinancialPersonDataOtherCountAggregateInputType | true
	_avg?: FinancialPersonDataOtherAvgAggregateInputType
	_sum?: FinancialPersonDataOtherSumAggregateInputType
	_min?: FinancialPersonDataOtherMinAggregateInputType
	_max?: FinancialPersonDataOtherMaxAggregateInputType
}

export type FinancialPersonDataOtherGroupByOutputType = {
	personId: number
	description: string | null
	email: string | null
	address: string | null
	postalCode: string | null
	city: string | null
	iban: string | null
	_count: FinancialPersonDataOtherCountAggregateOutputType | null
	_avg: FinancialPersonDataOtherAvgAggregateOutputType | null
	_sum: FinancialPersonDataOtherSumAggregateOutputType | null
	_min: FinancialPersonDataOtherMinAggregateOutputType | null
	_max: FinancialPersonDataOtherMaxAggregateOutputType | null
}

type GetFinancialPersonDataOtherGroupByPayload<T extends FinancialPersonDataOtherGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<FinancialPersonDataOtherGroupByOutputType, T['by']> & {
			[P in keyof T & keyof FinancialPersonDataOtherGroupByOutputType]: P extends '_count'
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], FinancialPersonDataOtherGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], FinancialPersonDataOtherGroupByOutputType[P]>
		}
	>
>

export type FinancialPersonDataOtherWhereInput = {
	AND?: Prisma.FinancialPersonDataOtherWhereInput | Prisma.FinancialPersonDataOtherWhereInput[]
	OR?: Prisma.FinancialPersonDataOtherWhereInput[]
	NOT?: Prisma.FinancialPersonDataOtherWhereInput | Prisma.FinancialPersonDataOtherWhereInput[]
	personId?: Prisma.IntFilter<'FinancialPersonDataOther'> | number
	description?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	email?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	address?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	postalCode?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	city?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	iban?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
	person?: Prisma.XOR<Prisma.FinancialPersonScalarRelationFilter, Prisma.FinancialPersonWhereInput>
}

export type FinancialPersonDataOtherOrderByWithRelationInput = {
	personId?: Prisma.SortOrder
	description?: Prisma.SortOrderInput | Prisma.SortOrder
	email?: Prisma.SortOrderInput | Prisma.SortOrder
	address?: Prisma.SortOrderInput | Prisma.SortOrder
	postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
	city?: Prisma.SortOrderInput | Prisma.SortOrder
	iban?: Prisma.SortOrderInput | Prisma.SortOrder
	person?: Prisma.FinancialPersonOrderByWithRelationInput
	_relevance?: Prisma.FinancialPersonDataOtherOrderByRelevanceInput
}

export type FinancialPersonDataOtherWhereUniqueInput = Prisma.AtLeast<
	{
		personId?: number
		AND?: Prisma.FinancialPersonDataOtherWhereInput | Prisma.FinancialPersonDataOtherWhereInput[]
		OR?: Prisma.FinancialPersonDataOtherWhereInput[]
		NOT?: Prisma.FinancialPersonDataOtherWhereInput | Prisma.FinancialPersonDataOtherWhereInput[]
		description?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		email?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		address?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		postalCode?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		city?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		iban?: Prisma.StringNullableFilter<'FinancialPersonDataOther'> | string | null
		person?: Prisma.XOR<Prisma.FinancialPersonScalarRelationFilter, Prisma.FinancialPersonWhereInput>
	},
	'personId'
>

export type FinancialPersonDataOtherOrderByWithAggregationInput = {
	personId?: Prisma.SortOrder
	description?: Prisma.SortOrderInput | Prisma.SortOrder
	email?: Prisma.SortOrderInput | Prisma.SortOrder
	address?: Prisma.SortOrderInput | Prisma.SortOrder
	postalCode?: Prisma.SortOrderInput | Prisma.SortOrder
	city?: Prisma.SortOrderInput | Prisma.SortOrder
	iban?: Prisma.SortOrderInput | Prisma.SortOrder
	_count?: Prisma.FinancialPersonDataOtherCountOrderByAggregateInput
	_avg?: Prisma.FinancialPersonDataOtherAvgOrderByAggregateInput
	_max?: Prisma.FinancialPersonDataOtherMaxOrderByAggregateInput
	_min?: Prisma.FinancialPersonDataOtherMinOrderByAggregateInput
	_sum?: Prisma.FinancialPersonDataOtherSumOrderByAggregateInput
}

export type FinancialPersonDataOtherScalarWhereWithAggregatesInput = {
	AND?: Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput | Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput[]
	OR?: Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput[]
	NOT?: Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput | Prisma.FinancialPersonDataOtherScalarWhereWithAggregatesInput[]
	personId?: Prisma.IntWithAggregatesFilter<'FinancialPersonDataOther'> | number
	description?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
	email?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
	address?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
	postalCode?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
	city?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
	iban?: Prisma.StringNullableWithAggregatesFilter<'FinancialPersonDataOther'> | string | null
}

export type FinancialPersonDataOtherCreateInput = {
	description?: string | null
	email?: string | null
	address?: string | null
	postalCode?: string | null
	city?: string | null
	iban?: string | null
	person: Prisma.FinancialPersonCreateNestedOneWithoutFinancialPersonDataOtherInput
}

export type FinancialPersonDataOtherUncheckedCreateInput = {
	personId: number
	description?: string | null
	email?: string | null
	address?: string | null
	postalCode?: string | null
	city?: string | null
	iban?: string | null
}

export type FinancialPersonDataOtherUpdateInput = {
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	person?: Prisma.FinancialPersonUpdateOneRequiredWithoutFinancialPersonDataOtherNestedInput
}

export type FinancialPersonDataOtherUncheckedUpdateInput = {
	personId?: Prisma.IntFieldUpdateOperationsInput | number
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FinancialPersonDataOtherCreateManyInput = {
	personId: number
	description?: string | null
	email?: string | null
	address?: string | null
	postalCode?: string | null
	city?: string | null
	iban?: string | null
}

export type FinancialPersonDataOtherUpdateManyMutationInput = {
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FinancialPersonDataOtherUncheckedUpdateManyInput = {
	personId?: Prisma.IntFieldUpdateOperationsInput | number
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FinancialPersonDataOtherNullableScalarRelationFilter = {
	is?: Prisma.FinancialPersonDataOtherWhereInput | null
	isNot?: Prisma.FinancialPersonDataOtherWhereInput | null
}

export type FinancialPersonDataOtherOrderByRelevanceInput = {
	fields: Prisma.FinancialPersonDataOtherOrderByRelevanceFieldEnum | Prisma.FinancialPersonDataOtherOrderByRelevanceFieldEnum[]
	sort: Prisma.SortOrder
	search: string
}

export type FinancialPersonDataOtherCountOrderByAggregateInput = {
	personId?: Prisma.SortOrder
	description?: Prisma.SortOrder
	email?: Prisma.SortOrder
	address?: Prisma.SortOrder
	postalCode?: Prisma.SortOrder
	city?: Prisma.SortOrder
	iban?: Prisma.SortOrder
}

export type FinancialPersonDataOtherAvgOrderByAggregateInput = {
	personId?: Prisma.SortOrder
}

export type FinancialPersonDataOtherMaxOrderByAggregateInput = {
	personId?: Prisma.SortOrder
	description?: Prisma.SortOrder
	email?: Prisma.SortOrder
	address?: Prisma.SortOrder
	postalCode?: Prisma.SortOrder
	city?: Prisma.SortOrder
	iban?: Prisma.SortOrder
}

export type FinancialPersonDataOtherMinOrderByAggregateInput = {
	personId?: Prisma.SortOrder
	description?: Prisma.SortOrder
	email?: Prisma.SortOrder
	address?: Prisma.SortOrder
	postalCode?: Prisma.SortOrder
	city?: Prisma.SortOrder
	iban?: Prisma.SortOrder
}

export type FinancialPersonDataOtherSumOrderByAggregateInput = {
	personId?: Prisma.SortOrder
}

export type FinancialPersonDataOtherCreateNestedOneWithoutPersonInput = {
	create?: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
	connectOrCreate?: Prisma.FinancialPersonDataOtherCreateOrConnectWithoutPersonInput
	connect?: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

export type FinancialPersonDataOtherUncheckedCreateNestedOneWithoutPersonInput = {
	create?: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
	connectOrCreate?: Prisma.FinancialPersonDataOtherCreateOrConnectWithoutPersonInput
	connect?: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

export type FinancialPersonDataOtherUpdateOneWithoutPersonNestedInput = {
	create?: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
	connectOrCreate?: Prisma.FinancialPersonDataOtherCreateOrConnectWithoutPersonInput
	upsert?: Prisma.FinancialPersonDataOtherUpsertWithoutPersonInput
	disconnect?: Prisma.FinancialPersonDataOtherWhereInput | boolean
	delete?: Prisma.FinancialPersonDataOtherWhereInput | boolean
	connect?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.FinancialPersonDataOtherUpdateToOneWithWhereWithoutPersonInput,
			Prisma.FinancialPersonDataOtherUpdateWithoutPersonInput
		>,
		Prisma.FinancialPersonDataOtherUncheckedUpdateWithoutPersonInput
	>
}

export type FinancialPersonDataOtherUncheckedUpdateOneWithoutPersonNestedInput = {
	create?: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
	connectOrCreate?: Prisma.FinancialPersonDataOtherCreateOrConnectWithoutPersonInput
	upsert?: Prisma.FinancialPersonDataOtherUpsertWithoutPersonInput
	disconnect?: Prisma.FinancialPersonDataOtherWhereInput | boolean
	delete?: Prisma.FinancialPersonDataOtherWhereInput | boolean
	connect?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<
			Prisma.FinancialPersonDataOtherUpdateToOneWithWhereWithoutPersonInput,
			Prisma.FinancialPersonDataOtherUpdateWithoutPersonInput
		>,
		Prisma.FinancialPersonDataOtherUncheckedUpdateWithoutPersonInput
	>
}

export type FinancialPersonDataOtherCreateWithoutPersonInput = {
	description?: string | null
	email?: string | null
	address?: string | null
	postalCode?: string | null
	city?: string | null
	iban?: string | null
}

export type FinancialPersonDataOtherUncheckedCreateWithoutPersonInput = {
	description?: string | null
	email?: string | null
	address?: string | null
	postalCode?: string | null
	city?: string | null
	iban?: string | null
}

export type FinancialPersonDataOtherCreateOrConnectWithoutPersonInput = {
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
	create: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
}

export type FinancialPersonDataOtherUpsertWithoutPersonInput = {
	update: Prisma.XOR<
		Prisma.FinancialPersonDataOtherUpdateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedUpdateWithoutPersonInput
	>
	create: Prisma.XOR<
		Prisma.FinancialPersonDataOtherCreateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedCreateWithoutPersonInput
	>
	where?: Prisma.FinancialPersonDataOtherWhereInput
}

export type FinancialPersonDataOtherUpdateToOneWithWhereWithoutPersonInput = {
	where?: Prisma.FinancialPersonDataOtherWhereInput
	data: Prisma.XOR<
		Prisma.FinancialPersonDataOtherUpdateWithoutPersonInput,
		Prisma.FinancialPersonDataOtherUncheckedUpdateWithoutPersonInput
	>
}

export type FinancialPersonDataOtherUpdateWithoutPersonInput = {
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FinancialPersonDataOtherUncheckedUpdateWithoutPersonInput = {
	description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	postalCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FinancialPersonDataOtherSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetSelect<
		{
			personId?: boolean
			description?: boolean
			email?: boolean
			address?: boolean
			postalCode?: boolean
			city?: boolean
			iban?: boolean
			person?: boolean | Prisma.FinancialPersonDefaultArgs<ExtArgs>
		},
		ExtArgs['result']['financialPersonDataOther']
	>

export type FinancialPersonDataOtherSelectScalar = {
	personId?: boolean
	description?: boolean
	email?: boolean
	address?: boolean
	postalCode?: boolean
	city?: boolean
	iban?: boolean
}

export type FinancialPersonDataOtherOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetOmit<
		'personId' | 'description' | 'email' | 'address' | 'postalCode' | 'city' | 'iban',
		ExtArgs['result']['financialPersonDataOther']
	>
export type FinancialPersonDataOtherInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	{
		person?: boolean | Prisma.FinancialPersonDefaultArgs<ExtArgs>
	}

export type $FinancialPersonDataOtherPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	{
		name: 'FinancialPersonDataOther'
		objects: {
			person: Prisma.$FinancialPersonPayload<ExtArgs>
		}
		scalars: runtime.Types.Extensions.GetPayloadResult<
			{
				personId: number
				description: string | null
				email: string | null
				address: string | null
				postalCode: string | null
				city: string | null
				iban: string | null
			},
			ExtArgs['result']['financialPersonDataOther']
		>
		composites: {}
	}

export type FinancialPersonDataOtherGetPayload<S extends boolean | null | undefined | FinancialPersonDataOtherDefaultArgs> =
	runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload, S>

export type FinancialPersonDataOtherCountArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<FinancialPersonDataOtherFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
	select?: FinancialPersonDataOtherCountAggregateInputType | true
}

export interface FinancialPersonDataOtherDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FinancialPersonDataOther']; meta: { name: 'FinancialPersonDataOther' } }
	/**
	 * Find zero or one FinancialPersonDataOther that matches the filter.
	 * @param {FinancialPersonDataOtherFindUniqueArgs} args - Arguments to find a FinancialPersonDataOther
	 * @example
	 * // Get one FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends FinancialPersonDataOtherFindUniqueArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherFindUniqueArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find one FinancialPersonDataOther that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {FinancialPersonDataOtherFindUniqueOrThrowArgs} args - Arguments to find a FinancialPersonDataOther
	 * @example
	 * // Get one FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends FinancialPersonDataOtherFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherFindUniqueOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first FinancialPersonDataOther that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherFindFirstArgs} args - Arguments to find a FinancialPersonDataOther
	 * @example
	 * // Get one FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends FinancialPersonDataOtherFindFirstArgs>(
		args?: Prisma.SelectSubset<T, FinancialPersonDataOtherFindFirstArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first FinancialPersonDataOther that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherFindFirstOrThrowArgs} args - Arguments to find a FinancialPersonDataOther
	 * @example
	 * // Get one FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends FinancialPersonDataOtherFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, FinancialPersonDataOtherFindFirstOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find zero or more FinancialPersonDataOthers that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all FinancialPersonDataOthers
	 * const financialPersonDataOthers = await prisma.financialPersonDataOther.findMany()
	 *
	 * // Get first 10 FinancialPersonDataOthers
	 * const financialPersonDataOthers = await prisma.financialPersonDataOther.findMany({ take: 10 })
	 *
	 * // Only select the `personId`
	 * const financialPersonDataOtherWithPersonIdOnly = await prisma.financialPersonDataOther.findMany({ select: { personId: true } })
	 *
	 */
	findMany<T extends FinancialPersonDataOtherFindManyArgs>(
		args?: Prisma.SelectSubset<T, FinancialPersonDataOtherFindManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
	>

	/**
	 * Create a FinancialPersonDataOther.
	 * @param {FinancialPersonDataOtherCreateArgs} args - Arguments to create a FinancialPersonDataOther.
	 * @example
	 * // Create one FinancialPersonDataOther
	 * const FinancialPersonDataOther = await prisma.financialPersonDataOther.create({
	 *   data: {
	 *     // ... data to create a FinancialPersonDataOther
	 *   }
	 * })
	 *
	 */
	create<T extends FinancialPersonDataOtherCreateArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherCreateArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Create many FinancialPersonDataOthers.
	 * @param {FinancialPersonDataOtherCreateManyArgs} args - Arguments to create many FinancialPersonDataOthers.
	 * @example
	 * // Create many FinancialPersonDataOthers
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends FinancialPersonDataOtherCreateManyArgs>(
		args?: Prisma.SelectSubset<T, FinancialPersonDataOtherCreateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Delete a FinancialPersonDataOther.
	 * @param {FinancialPersonDataOtherDeleteArgs} args - Arguments to delete one FinancialPersonDataOther.
	 * @example
	 * // Delete one FinancialPersonDataOther
	 * const FinancialPersonDataOther = await prisma.financialPersonDataOther.delete({
	 *   where: {
	 *     // ... filter to delete one FinancialPersonDataOther
	 *   }
	 * })
	 *
	 */
	delete<T extends FinancialPersonDataOtherDeleteArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherDeleteArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Update one FinancialPersonDataOther.
	 * @param {FinancialPersonDataOtherUpdateArgs} args - Arguments to update one FinancialPersonDataOther.
	 * @example
	 * // Update one FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends FinancialPersonDataOtherUpdateArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherUpdateArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Delete zero or more FinancialPersonDataOthers.
	 * @param {FinancialPersonDataOtherDeleteManyArgs} args - Arguments to filter FinancialPersonDataOthers to delete.
	 * @example
	 * // Delete a few FinancialPersonDataOthers
	 * const { count } = await prisma.financialPersonDataOther.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends FinancialPersonDataOtherDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, FinancialPersonDataOtherDeleteManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Update zero or more FinancialPersonDataOthers.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many FinancialPersonDataOthers
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends FinancialPersonDataOtherUpdateManyArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherUpdateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Create or update one FinancialPersonDataOther.
	 * @param {FinancialPersonDataOtherUpsertArgs} args - Arguments to update or create a FinancialPersonDataOther.
	 * @example
	 * // Update or create a FinancialPersonDataOther
	 * const financialPersonDataOther = await prisma.financialPersonDataOther.upsert({
	 *   create: {
	 *     // ... data to create a FinancialPersonDataOther
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the FinancialPersonDataOther we want to update
	 *   }
	 * })
	 */
	upsert<T extends FinancialPersonDataOtherUpsertArgs>(
		args: Prisma.SelectSubset<T, FinancialPersonDataOtherUpsertArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonDataOtherClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonDataOtherPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Count the number of FinancialPersonDataOthers.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherCountArgs} args - Arguments to filter FinancialPersonDataOthers to count.
	 * @example
	 * // Count the number of FinancialPersonDataOthers
	 * const count = await prisma.financialPersonDataOther.count({
	 *   where: {
	 *     // ... the filter for the FinancialPersonDataOthers we want to count
	 *   }
	 * })
	 **/
	count<T extends FinancialPersonDataOtherCountArgs>(
		args?: Prisma.Subset<T, FinancialPersonDataOtherCountArgs>,
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<'select', any>
			? T['select'] extends true
				? number
				: Prisma.GetScalarType<T['select'], FinancialPersonDataOtherCountAggregateOutputType>
			: number
	>

	/**
	 * Allows you to perform aggregations operations on a FinancialPersonDataOther.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends FinancialPersonDataOtherAggregateArgs>(
		args: Prisma.Subset<T, FinancialPersonDataOtherAggregateArgs>,
	): Prisma.PrismaPromise<GetFinancialPersonDataOtherAggregateType<T>>

	/**
	 * Group by FinancialPersonDataOther.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {FinancialPersonDataOtherGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends FinancialPersonDataOtherGroupByArgs,
		HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: FinancialPersonDataOtherGroupByArgs['orderBy'] }
			: { orderBy?: FinancialPersonDataOtherGroupByArgs['orderBy'] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T['having']>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
					}[HavingFields]
				: 'take' extends Prisma.Keys<T>
					? 'orderBy' extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: 'skip' extends Prisma.Keys<T>
						? 'orderBy' extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields],
	>(
		args: Prisma.SubsetIntersection<T, FinancialPersonDataOtherGroupByArgs, OrderByArg> & InputErrors,
	): {} extends InputErrors ? GetFinancialPersonDataOtherGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
	/**
	 * Fields of the FinancialPersonDataOther model
	 */
	readonly fields: FinancialPersonDataOtherFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for FinancialPersonDataOther.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FinancialPersonDataOtherClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: 'PrismaPromise'
	person<T extends Prisma.FinancialPersonDefaultArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.FinancialPersonDefaultArgs<ExtArgs>>,
	): Prisma.Prisma__FinancialPersonClient<
		runtime.Types.Result.GetResult<Prisma.$FinancialPersonPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | Null,
		Null,
		ExtArgs,
		GlobalOmitOptions
	>
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
	): runtime.Types.Utils.JsPromise<T | TResult>
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the FinancialPersonDataOther model
 */
export interface FinancialPersonDataOtherFieldRefs {
	readonly personId: Prisma.FieldRef<'FinancialPersonDataOther', 'Int'>
	readonly description: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
	readonly email: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
	readonly address: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
	readonly postalCode: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
	readonly city: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
	readonly iban: Prisma.FieldRef<'FinancialPersonDataOther', 'String'>
}

// Custom InputTypes
/**
 * FinancialPersonDataOther findUnique
 */
export type FinancialPersonDataOtherFindUniqueArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter, which FinancialPersonDataOther to fetch.
	 */
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

/**
 * FinancialPersonDataOther findUniqueOrThrow
 */
export type FinancialPersonDataOtherFindUniqueOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter, which FinancialPersonDataOther to fetch.
	 */
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

/**
 * FinancialPersonDataOther findFirst
 */
export type FinancialPersonDataOtherFindFirstArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter, which FinancialPersonDataOther to fetch.
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of FinancialPersonDataOthers to fetch.
	 */
	orderBy?: Prisma.FinancialPersonDataOtherOrderByWithRelationInput | Prisma.FinancialPersonDataOtherOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for FinancialPersonDataOthers.
	 */
	cursor?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` FinancialPersonDataOthers from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` FinancialPersonDataOthers.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of FinancialPersonDataOthers.
	 */
	distinct?: Prisma.FinancialPersonDataOtherScalarFieldEnum | Prisma.FinancialPersonDataOtherScalarFieldEnum[]
}

/**
 * FinancialPersonDataOther findFirstOrThrow
 */
export type FinancialPersonDataOtherFindFirstOrThrowArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter, which FinancialPersonDataOther to fetch.
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of FinancialPersonDataOthers to fetch.
	 */
	orderBy?: Prisma.FinancialPersonDataOtherOrderByWithRelationInput | Prisma.FinancialPersonDataOtherOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for FinancialPersonDataOthers.
	 */
	cursor?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` FinancialPersonDataOthers from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` FinancialPersonDataOthers.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of FinancialPersonDataOthers.
	 */
	distinct?: Prisma.FinancialPersonDataOtherScalarFieldEnum | Prisma.FinancialPersonDataOtherScalarFieldEnum[]
}

/**
 * FinancialPersonDataOther findMany
 */
export type FinancialPersonDataOtherFindManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter, which FinancialPersonDataOthers to fetch.
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of FinancialPersonDataOthers to fetch.
	 */
	orderBy?: Prisma.FinancialPersonDataOtherOrderByWithRelationInput | Prisma.FinancialPersonDataOtherOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing FinancialPersonDataOthers.
	 */
	cursor?: Prisma.FinancialPersonDataOtherWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` FinancialPersonDataOthers from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` FinancialPersonDataOthers.
	 */
	skip?: number
	distinct?: Prisma.FinancialPersonDataOtherScalarFieldEnum | Prisma.FinancialPersonDataOtherScalarFieldEnum[]
}

/**
 * FinancialPersonDataOther create
 */
export type FinancialPersonDataOtherCreateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * The data needed to create a FinancialPersonDataOther.
	 */
	data: Prisma.XOR<Prisma.FinancialPersonDataOtherCreateInput, Prisma.FinancialPersonDataOtherUncheckedCreateInput>
}

/**
 * FinancialPersonDataOther createMany
 */
export type FinancialPersonDataOtherCreateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * The data used to create many FinancialPersonDataOthers.
	 */
	data: Prisma.FinancialPersonDataOtherCreateManyInput | Prisma.FinancialPersonDataOtherCreateManyInput[]
	skipDuplicates?: boolean
}

/**
 * FinancialPersonDataOther update
 */
export type FinancialPersonDataOtherUpdateArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * The data needed to update a FinancialPersonDataOther.
	 */
	data: Prisma.XOR<Prisma.FinancialPersonDataOtherUpdateInput, Prisma.FinancialPersonDataOtherUncheckedUpdateInput>
	/**
	 * Choose, which FinancialPersonDataOther to update.
	 */
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

/**
 * FinancialPersonDataOther updateMany
 */
export type FinancialPersonDataOtherUpdateManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * The data used to update FinancialPersonDataOthers.
	 */
	data: Prisma.XOR<Prisma.FinancialPersonDataOtherUpdateManyMutationInput, Prisma.FinancialPersonDataOtherUncheckedUpdateManyInput>
	/**
	 * Filter which FinancialPersonDataOthers to update
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * Limit how many FinancialPersonDataOthers to update.
	 */
	limit?: number
}

/**
 * FinancialPersonDataOther upsert
 */
export type FinancialPersonDataOtherUpsertArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * The filter to search for the FinancialPersonDataOther to update in case it exists.
	 */
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
	/**
	 * In case the FinancialPersonDataOther found by the `where` argument doesn't exist, create a new FinancialPersonDataOther with this data.
	 */
	create: Prisma.XOR<Prisma.FinancialPersonDataOtherCreateInput, Prisma.FinancialPersonDataOtherUncheckedCreateInput>
	/**
	 * In case the FinancialPersonDataOther was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.FinancialPersonDataOtherUpdateInput, Prisma.FinancialPersonDataOtherUncheckedUpdateInput>
}

/**
 * FinancialPersonDataOther delete
 */
export type FinancialPersonDataOtherDeleteArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
	/**
	 * Filter which FinancialPersonDataOther to delete.
	 */
	where: Prisma.FinancialPersonDataOtherWhereUniqueInput
}

/**
 * FinancialPersonDataOther deleteMany
 */
export type FinancialPersonDataOtherDeleteManyArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Filter which FinancialPersonDataOthers to delete
	 */
	where?: Prisma.FinancialPersonDataOtherWhereInput
	/**
	 * Limit how many FinancialPersonDataOthers to delete.
	 */
	limit?: number
}

/**
 * FinancialPersonDataOther without action
 */
export type FinancialPersonDataOtherDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the FinancialPersonDataOther
	 */
	select?: Prisma.FinancialPersonDataOtherSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the FinancialPersonDataOther
	 */
	omit?: Prisma.FinancialPersonDataOtherOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.FinancialPersonDataOtherInclude<ExtArgs> | null
}
