/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Streeplijst` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model Streeplijst
 *
 */
export type StreeplijstModel = runtime.Types.Result.DefaultSelection<Prisma.$StreeplijstPayload>

export type AggregateStreeplijst = {
	_count: StreeplijstCountAggregateOutputType | null
	_avg: StreeplijstAvgAggregateOutputType | null
	_sum: StreeplijstSumAggregateOutputType | null
	_min: StreeplijstMinAggregateOutputType | null
	_max: StreeplijstMaxAggregateOutputType | null
}

export type StreeplijstAvgAggregateOutputType = {
	id: number | null
	userId: number | null
}

export type StreeplijstSumAggregateOutputType = {
	id: number | null
	userId: number | null
}

export type StreeplijstMinAggregateOutputType = {
	id: number | null
	createdAt: Date | null
	updatedAt: Date | null
	startDate: Date | null
	endDate: Date | null
	userId: number | null
	notes: string | null
}

export type StreeplijstMaxAggregateOutputType = {
	id: number | null
	createdAt: Date | null
	updatedAt: Date | null
	startDate: Date | null
	endDate: Date | null
	userId: number | null
	notes: string | null
}

export type StreeplijstCountAggregateOutputType = {
	id: number
	createdAt: number
	updatedAt: number
	startDate: number
	endDate: number
	userId: number
	notes: number
	_all: number
}

export type StreeplijstAvgAggregateInputType = {
	id?: true
	userId?: true
}

export type StreeplijstSumAggregateInputType = {
	id?: true
	userId?: true
}

export type StreeplijstMinAggregateInputType = {
	id?: true
	createdAt?: true
	updatedAt?: true
	startDate?: true
	endDate?: true
	userId?: true
	notes?: true
}

export type StreeplijstMaxAggregateInputType = {
	id?: true
	createdAt?: true
	updatedAt?: true
	startDate?: true
	endDate?: true
	userId?: true
	notes?: true
}

export type StreeplijstCountAggregateInputType = {
	id?: true
	createdAt?: true
	updatedAt?: true
	startDate?: true
	endDate?: true
	userId?: true
	notes?: true
	_all?: true
}

export type StreeplijstAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which Streeplijst to aggregate.
	 */
	where?: Prisma.StreeplijstWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Streeplijsts to fetch.
	 */
	orderBy?: Prisma.StreeplijstOrderByWithRelationInput | Prisma.StreeplijstOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the start position
	 */
	cursor?: Prisma.StreeplijstWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Streeplijsts from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Streeplijsts.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Count returned Streeplijsts
	 **/
	_count?: true | StreeplijstCountAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to average
	 **/
	_avg?: StreeplijstAvgAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to sum
	 **/
	_sum?: StreeplijstSumAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the minimum value
	 **/
	_min?: StreeplijstMinAggregateInputType
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
	 *
	 * Select which fields to find the maximum value
	 **/
	_max?: StreeplijstMaxAggregateInputType
}

export type GetStreeplijstAggregateType<T extends StreeplijstAggregateArgs> = {
	[P in keyof T & keyof AggregateStreeplijst]: P extends '_count' | 'count'
		? T[P] extends true
			? number
			: Prisma.GetScalarType<T[P], AggregateStreeplijst[P]>
		: Prisma.GetScalarType<T[P], AggregateStreeplijst[P]>
}

export type StreeplijstGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	where?: Prisma.StreeplijstWhereInput
	orderBy?: Prisma.StreeplijstOrderByWithAggregationInput | Prisma.StreeplijstOrderByWithAggregationInput[]
	by: Prisma.StreeplijstScalarFieldEnum[] | Prisma.StreeplijstScalarFieldEnum
	having?: Prisma.StreeplijstScalarWhereWithAggregatesInput
	take?: number
	skip?: number
	_count?: StreeplijstCountAggregateInputType | true
	_avg?: StreeplijstAvgAggregateInputType
	_sum?: StreeplijstSumAggregateInputType
	_min?: StreeplijstMinAggregateInputType
	_max?: StreeplijstMaxAggregateInputType
}

export type StreeplijstGroupByOutputType = {
	id: number
	createdAt: Date
	updatedAt: Date
	startDate: Date | null
	endDate: Date | null
	userId: number | null
	notes: string | null
	_count: StreeplijstCountAggregateOutputType | null
	_avg: StreeplijstAvgAggregateOutputType | null
	_sum: StreeplijstSumAggregateOutputType | null
	_min: StreeplijstMinAggregateOutputType | null
	_max: StreeplijstMaxAggregateOutputType | null
}

type GetStreeplijstGroupByPayload<T extends StreeplijstGroupByArgs> = Prisma.PrismaPromise<
	Array<
		Prisma.PickEnumerable<StreeplijstGroupByOutputType, T['by']> & {
			[P in keyof T & keyof StreeplijstGroupByOutputType]: P extends '_count'
				? T[P] extends boolean
					? number
					: Prisma.GetScalarType<T[P], StreeplijstGroupByOutputType[P]>
				: Prisma.GetScalarType<T[P], StreeplijstGroupByOutputType[P]>
		}
	>
>

export type StreeplijstWhereInput = {
	AND?: Prisma.StreeplijstWhereInput | Prisma.StreeplijstWhereInput[]
	OR?: Prisma.StreeplijstWhereInput[]
	NOT?: Prisma.StreeplijstWhereInput | Prisma.StreeplijstWhereInput[]
	id?: Prisma.IntFilter<'Streeplijst'> | number
	createdAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
	updatedAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
	startDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
	endDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
	userId?: Prisma.IntNullableFilter<'Streeplijst'> | number | null
	notes?: Prisma.StringNullableFilter<'Streeplijst'> | string | null
	treasurer?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
	sales?: Prisma.JournalListRelationFilter
}

export type StreeplijstOrderByWithRelationInput = {
	id?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	startDate?: Prisma.SortOrderInput | Prisma.SortOrder
	endDate?: Prisma.SortOrderInput | Prisma.SortOrder
	userId?: Prisma.SortOrderInput | Prisma.SortOrder
	notes?: Prisma.SortOrderInput | Prisma.SortOrder
	treasurer?: Prisma.UserOrderByWithRelationInput
	sales?: Prisma.JournalOrderByRelationAggregateInput
	_relevance?: Prisma.StreeplijstOrderByRelevanceInput
}

export type StreeplijstWhereUniqueInput = Prisma.AtLeast<
	{
		id?: number
		AND?: Prisma.StreeplijstWhereInput | Prisma.StreeplijstWhereInput[]
		OR?: Prisma.StreeplijstWhereInput[]
		NOT?: Prisma.StreeplijstWhereInput | Prisma.StreeplijstWhereInput[]
		createdAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
		updatedAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
		startDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
		endDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
		userId?: Prisma.IntNullableFilter<'Streeplijst'> | number | null
		notes?: Prisma.StringNullableFilter<'Streeplijst'> | string | null
		treasurer?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
		sales?: Prisma.JournalListRelationFilter
	},
	'id'
>

export type StreeplijstOrderByWithAggregationInput = {
	id?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	startDate?: Prisma.SortOrderInput | Prisma.SortOrder
	endDate?: Prisma.SortOrderInput | Prisma.SortOrder
	userId?: Prisma.SortOrderInput | Prisma.SortOrder
	notes?: Prisma.SortOrderInput | Prisma.SortOrder
	_count?: Prisma.StreeplijstCountOrderByAggregateInput
	_avg?: Prisma.StreeplijstAvgOrderByAggregateInput
	_max?: Prisma.StreeplijstMaxOrderByAggregateInput
	_min?: Prisma.StreeplijstMinOrderByAggregateInput
	_sum?: Prisma.StreeplijstSumOrderByAggregateInput
}

export type StreeplijstScalarWhereWithAggregatesInput = {
	AND?: Prisma.StreeplijstScalarWhereWithAggregatesInput | Prisma.StreeplijstScalarWhereWithAggregatesInput[]
	OR?: Prisma.StreeplijstScalarWhereWithAggregatesInput[]
	NOT?: Prisma.StreeplijstScalarWhereWithAggregatesInput | Prisma.StreeplijstScalarWhereWithAggregatesInput[]
	id?: Prisma.IntWithAggregatesFilter<'Streeplijst'> | number
	createdAt?: Prisma.DateTimeWithAggregatesFilter<'Streeplijst'> | Date | string
	updatedAt?: Prisma.DateTimeWithAggregatesFilter<'Streeplijst'> | Date | string
	startDate?: Prisma.DateTimeNullableWithAggregatesFilter<'Streeplijst'> | Date | string | null
	endDate?: Prisma.DateTimeNullableWithAggregatesFilter<'Streeplijst'> | Date | string | null
	userId?: Prisma.IntNullableWithAggregatesFilter<'Streeplijst'> | number | null
	notes?: Prisma.StringNullableWithAggregatesFilter<'Streeplijst'> | string | null
}

export type StreeplijstCreateInput = {
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	notes?: string | null
	treasurer?: Prisma.UserCreateNestedOneWithoutStreeplijstInput
	sales?: Prisma.JournalCreateNestedManyWithoutStreeplijstInput
}

export type StreeplijstUncheckedCreateInput = {
	id?: number
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	userId?: number | null
	notes?: string | null
	sales?: Prisma.JournalUncheckedCreateNestedManyWithoutStreeplijstInput
}

export type StreeplijstUpdateInput = {
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	treasurer?: Prisma.UserUpdateOneWithoutStreeplijstNestedInput
	sales?: Prisma.JournalUpdateManyWithoutStreeplijstNestedInput
}

export type StreeplijstUncheckedUpdateInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	sales?: Prisma.JournalUncheckedUpdateManyWithoutStreeplijstNestedInput
}

export type StreeplijstCreateManyInput = {
	id?: number
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	userId?: number | null
	notes?: string | null
}

export type StreeplijstUpdateManyMutationInput = {
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StreeplijstUncheckedUpdateManyInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StreeplijstListRelationFilter = {
	every?: Prisma.StreeplijstWhereInput
	some?: Prisma.StreeplijstWhereInput
	none?: Prisma.StreeplijstWhereInput
}

export type StreeplijstOrderByRelationAggregateInput = {
	_count?: Prisma.SortOrder
}

export type StreeplijstOrderByRelevanceInput = {
	fields: Prisma.StreeplijstOrderByRelevanceFieldEnum | Prisma.StreeplijstOrderByRelevanceFieldEnum[]
	sort: Prisma.SortOrder
	search: string
}

export type StreeplijstCountOrderByAggregateInput = {
	id?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	startDate?: Prisma.SortOrder
	endDate?: Prisma.SortOrder
	userId?: Prisma.SortOrder
	notes?: Prisma.SortOrder
}

export type StreeplijstAvgOrderByAggregateInput = {
	id?: Prisma.SortOrder
	userId?: Prisma.SortOrder
}

export type StreeplijstMaxOrderByAggregateInput = {
	id?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	startDate?: Prisma.SortOrder
	endDate?: Prisma.SortOrder
	userId?: Prisma.SortOrder
	notes?: Prisma.SortOrder
}

export type StreeplijstMinOrderByAggregateInput = {
	id?: Prisma.SortOrder
	createdAt?: Prisma.SortOrder
	updatedAt?: Prisma.SortOrder
	startDate?: Prisma.SortOrder
	endDate?: Prisma.SortOrder
	userId?: Prisma.SortOrder
	notes?: Prisma.SortOrder
}

export type StreeplijstSumOrderByAggregateInput = {
	id?: Prisma.SortOrder
	userId?: Prisma.SortOrder
}

export type StreeplijstNullableScalarRelationFilter = {
	is?: Prisma.StreeplijstWhereInput | null
	isNot?: Prisma.StreeplijstWhereInput | null
}

export type StreeplijstCreateNestedManyWithoutTreasurerInput = {
	create?:
		| Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
		| Prisma.StreeplijstCreateWithoutTreasurerInput[]
		| Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput[]
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput | Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput[]
	createMany?: Prisma.StreeplijstCreateManyTreasurerInputEnvelope
	connect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
}

export type StreeplijstUncheckedCreateNestedManyWithoutTreasurerInput = {
	create?:
		| Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
		| Prisma.StreeplijstCreateWithoutTreasurerInput[]
		| Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput[]
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput | Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput[]
	createMany?: Prisma.StreeplijstCreateManyTreasurerInputEnvelope
	connect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
}

export type StreeplijstUpdateManyWithoutTreasurerNestedInput = {
	create?:
		| Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
		| Prisma.StreeplijstCreateWithoutTreasurerInput[]
		| Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput[]
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput | Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput[]
	upsert?: Prisma.StreeplijstUpsertWithWhereUniqueWithoutTreasurerInput | Prisma.StreeplijstUpsertWithWhereUniqueWithoutTreasurerInput[]
	createMany?: Prisma.StreeplijstCreateManyTreasurerInputEnvelope
	set?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	disconnect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	delete?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	connect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	update?: Prisma.StreeplijstUpdateWithWhereUniqueWithoutTreasurerInput | Prisma.StreeplijstUpdateWithWhereUniqueWithoutTreasurerInput[]
	updateMany?: Prisma.StreeplijstUpdateManyWithWhereWithoutTreasurerInput | Prisma.StreeplijstUpdateManyWithWhereWithoutTreasurerInput[]
	deleteMany?: Prisma.StreeplijstScalarWhereInput | Prisma.StreeplijstScalarWhereInput[]
}

export type StreeplijstUncheckedUpdateManyWithoutTreasurerNestedInput = {
	create?:
		| Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
		| Prisma.StreeplijstCreateWithoutTreasurerInput[]
		| Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput[]
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput | Prisma.StreeplijstCreateOrConnectWithoutTreasurerInput[]
	upsert?: Prisma.StreeplijstUpsertWithWhereUniqueWithoutTreasurerInput | Prisma.StreeplijstUpsertWithWhereUniqueWithoutTreasurerInput[]
	createMany?: Prisma.StreeplijstCreateManyTreasurerInputEnvelope
	set?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	disconnect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	delete?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	connect?: Prisma.StreeplijstWhereUniqueInput | Prisma.StreeplijstWhereUniqueInput[]
	update?: Prisma.StreeplijstUpdateWithWhereUniqueWithoutTreasurerInput | Prisma.StreeplijstUpdateWithWhereUniqueWithoutTreasurerInput[]
	updateMany?: Prisma.StreeplijstUpdateManyWithWhereWithoutTreasurerInput | Prisma.StreeplijstUpdateManyWithWhereWithoutTreasurerInput[]
	deleteMany?: Prisma.StreeplijstScalarWhereInput | Prisma.StreeplijstScalarWhereInput[]
}

export type StreeplijstCreateNestedOneWithoutSalesInput = {
	create?: Prisma.XOR<Prisma.StreeplijstCreateWithoutSalesInput, Prisma.StreeplijstUncheckedCreateWithoutSalesInput>
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutSalesInput
	connect?: Prisma.StreeplijstWhereUniqueInput
}

export type StreeplijstUpdateOneWithoutSalesNestedInput = {
	create?: Prisma.XOR<Prisma.StreeplijstCreateWithoutSalesInput, Prisma.StreeplijstUncheckedCreateWithoutSalesInput>
	connectOrCreate?: Prisma.StreeplijstCreateOrConnectWithoutSalesInput
	upsert?: Prisma.StreeplijstUpsertWithoutSalesInput
	disconnect?: Prisma.StreeplijstWhereInput | boolean
	delete?: Prisma.StreeplijstWhereInput | boolean
	connect?: Prisma.StreeplijstWhereUniqueInput
	update?: Prisma.XOR<
		Prisma.XOR<Prisma.StreeplijstUpdateToOneWithWhereWithoutSalesInput, Prisma.StreeplijstUpdateWithoutSalesInput>,
		Prisma.StreeplijstUncheckedUpdateWithoutSalesInput
	>
}

export type StreeplijstCreateWithoutTreasurerInput = {
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	notes?: string | null
	sales?: Prisma.JournalCreateNestedManyWithoutStreeplijstInput
}

export type StreeplijstUncheckedCreateWithoutTreasurerInput = {
	id?: number
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	notes?: string | null
	sales?: Prisma.JournalUncheckedCreateNestedManyWithoutStreeplijstInput
}

export type StreeplijstCreateOrConnectWithoutTreasurerInput = {
	where: Prisma.StreeplijstWhereUniqueInput
	create: Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
}

export type StreeplijstCreateManyTreasurerInputEnvelope = {
	data: Prisma.StreeplijstCreateManyTreasurerInput | Prisma.StreeplijstCreateManyTreasurerInput[]
	skipDuplicates?: boolean
}

export type StreeplijstUpsertWithWhereUniqueWithoutTreasurerInput = {
	where: Prisma.StreeplijstWhereUniqueInput
	update: Prisma.XOR<Prisma.StreeplijstUpdateWithoutTreasurerInput, Prisma.StreeplijstUncheckedUpdateWithoutTreasurerInput>
	create: Prisma.XOR<Prisma.StreeplijstCreateWithoutTreasurerInput, Prisma.StreeplijstUncheckedCreateWithoutTreasurerInput>
}

export type StreeplijstUpdateWithWhereUniqueWithoutTreasurerInput = {
	where: Prisma.StreeplijstWhereUniqueInput
	data: Prisma.XOR<Prisma.StreeplijstUpdateWithoutTreasurerInput, Prisma.StreeplijstUncheckedUpdateWithoutTreasurerInput>
}

export type StreeplijstUpdateManyWithWhereWithoutTreasurerInput = {
	where: Prisma.StreeplijstScalarWhereInput
	data: Prisma.XOR<Prisma.StreeplijstUpdateManyMutationInput, Prisma.StreeplijstUncheckedUpdateManyWithoutTreasurerInput>
}

export type StreeplijstScalarWhereInput = {
	AND?: Prisma.StreeplijstScalarWhereInput | Prisma.StreeplijstScalarWhereInput[]
	OR?: Prisma.StreeplijstScalarWhereInput[]
	NOT?: Prisma.StreeplijstScalarWhereInput | Prisma.StreeplijstScalarWhereInput[]
	id?: Prisma.IntFilter<'Streeplijst'> | number
	createdAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
	updatedAt?: Prisma.DateTimeFilter<'Streeplijst'> | Date | string
	startDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
	endDate?: Prisma.DateTimeNullableFilter<'Streeplijst'> | Date | string | null
	userId?: Prisma.IntNullableFilter<'Streeplijst'> | number | null
	notes?: Prisma.StringNullableFilter<'Streeplijst'> | string | null
}

export type StreeplijstCreateWithoutSalesInput = {
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	notes?: string | null
	treasurer?: Prisma.UserCreateNestedOneWithoutStreeplijstInput
}

export type StreeplijstUncheckedCreateWithoutSalesInput = {
	id?: number
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	userId?: number | null
	notes?: string | null
}

export type StreeplijstCreateOrConnectWithoutSalesInput = {
	where: Prisma.StreeplijstWhereUniqueInput
	create: Prisma.XOR<Prisma.StreeplijstCreateWithoutSalesInput, Prisma.StreeplijstUncheckedCreateWithoutSalesInput>
}

export type StreeplijstUpsertWithoutSalesInput = {
	update: Prisma.XOR<Prisma.StreeplijstUpdateWithoutSalesInput, Prisma.StreeplijstUncheckedUpdateWithoutSalesInput>
	create: Prisma.XOR<Prisma.StreeplijstCreateWithoutSalesInput, Prisma.StreeplijstUncheckedCreateWithoutSalesInput>
	where?: Prisma.StreeplijstWhereInput
}

export type StreeplijstUpdateToOneWithWhereWithoutSalesInput = {
	where?: Prisma.StreeplijstWhereInput
	data: Prisma.XOR<Prisma.StreeplijstUpdateWithoutSalesInput, Prisma.StreeplijstUncheckedUpdateWithoutSalesInput>
}

export type StreeplijstUpdateWithoutSalesInput = {
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	treasurer?: Prisma.UserUpdateOneWithoutStreeplijstNestedInput
}

export type StreeplijstUncheckedUpdateWithoutSalesInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StreeplijstCreateManyTreasurerInput = {
	id?: number
	createdAt?: Date | string
	updatedAt?: Date | string
	startDate?: Date | string | null
	endDate?: Date | string | null
	notes?: string | null
}

export type StreeplijstUpdateWithoutTreasurerInput = {
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	sales?: Prisma.JournalUpdateManyWithoutStreeplijstNestedInput
}

export type StreeplijstUncheckedUpdateWithoutTreasurerInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
	sales?: Prisma.JournalUncheckedUpdateManyWithoutStreeplijstNestedInput
}

export type StreeplijstUncheckedUpdateManyWithoutTreasurerInput = {
	id?: Prisma.IntFieldUpdateOperationsInput | number
	createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
	startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
	notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

/**
 * Count Type StreeplijstCountOutputType
 */

export type StreeplijstCountOutputType = {
	sales: number
}

export type StreeplijstCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	{
		sales?: boolean | StreeplijstCountOutputTypeCountSalesArgs
	}

/**
 * StreeplijstCountOutputType without action
 */
export type StreeplijstCountOutputTypeDefaultArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	/**
	 * Select specific fields to fetch from the StreeplijstCountOutputType
	 */
	select?: Prisma.StreeplijstCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StreeplijstCountOutputType without action
 */
export type StreeplijstCountOutputTypeCountSalesArgs<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
	where?: Prisma.JournalWhereInput
}

export type StreeplijstSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetSelect<
		{
			id?: boolean
			createdAt?: boolean
			updatedAt?: boolean
			startDate?: boolean
			endDate?: boolean
			userId?: boolean
			notes?: boolean
			treasurer?: boolean | Prisma.Streeplijst$treasurerArgs<ExtArgs>
			sales?: boolean | Prisma.Streeplijst$salesArgs<ExtArgs>
			_count?: boolean | Prisma.StreeplijstCountOutputTypeDefaultArgs<ExtArgs>
		},
		ExtArgs['result']['streeplijst']
	>

export type StreeplijstSelectScalar = {
	id?: boolean
	createdAt?: boolean
	updatedAt?: boolean
	startDate?: boolean
	endDate?: boolean
	userId?: boolean
	notes?: boolean
}

export type StreeplijstOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	runtime.Types.Extensions.GetOmit<
		'id' | 'createdAt' | 'updatedAt' | 'startDate' | 'endDate' | 'userId' | 'notes',
		ExtArgs['result']['streeplijst']
	>
export type StreeplijstInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	treasurer?: boolean | Prisma.Streeplijst$treasurerArgs<ExtArgs>
	sales?: boolean | Prisma.Streeplijst$salesArgs<ExtArgs>
	_count?: boolean | Prisma.StreeplijstCountOutputTypeDefaultArgs<ExtArgs>
}

export type $StreeplijstPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	name: 'Streeplijst'
	objects: {
		treasurer: Prisma.$UserPayload<ExtArgs> | null
		sales: Prisma.$JournalPayload<ExtArgs>[]
	}
	scalars: runtime.Types.Extensions.GetPayloadResult<
		{
			id: number
			createdAt: Date
			updatedAt: Date
			startDate: Date | null
			endDate: Date | null
			userId: number | null
			notes: string | null
		},
		ExtArgs['result']['streeplijst']
	>
	composites: {}
}

export type StreeplijstGetPayload<S extends boolean | null | undefined | StreeplijstDefaultArgs> = runtime.Types.Result.GetResult<
	Prisma.$StreeplijstPayload,
	S
>

export type StreeplijstCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
	StreeplijstFindManyArgs,
	'select' | 'include' | 'distinct' | 'omit'
> & {
	select?: StreeplijstCountAggregateInputType | true
}

export interface StreeplijstDelegate<
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> {
	[K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Streeplijst']; meta: { name: 'Streeplijst' } }
	/**
	 * Find zero or one Streeplijst that matches the filter.
	 * @param {StreeplijstFindUniqueArgs} args - Arguments to find a Streeplijst
	 * @example
	 * // Get one Streeplijst
	 * const streeplijst = await prisma.streeplijst.findUnique({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUnique<T extends StreeplijstFindUniqueArgs>(
		args: Prisma.SelectSubset<T, StreeplijstFindUniqueArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find one Streeplijst that matches the filter or throw an error with `error.code='P2025'`
	 * if no matches were found.
	 * @param {StreeplijstFindUniqueOrThrowArgs} args - Arguments to find a Streeplijst
	 * @example
	 * // Get one Streeplijst
	 * const streeplijst = await prisma.streeplijst.findUniqueOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findUniqueOrThrow<T extends StreeplijstFindUniqueOrThrowArgs>(
		args: Prisma.SelectSubset<T, StreeplijstFindUniqueOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first Streeplijst that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstFindFirstArgs} args - Arguments to find a Streeplijst
	 * @example
	 * // Get one Streeplijst
	 * const streeplijst = await prisma.streeplijst.findFirst({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirst<T extends StreeplijstFindFirstArgs>(
		args?: Prisma.SelectSubset<T, StreeplijstFindFirstArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find the first Streeplijst that matches the filter or
	 * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstFindFirstOrThrowArgs} args - Arguments to find a Streeplijst
	 * @example
	 * // Get one Streeplijst
	 * const streeplijst = await prisma.streeplijst.findFirstOrThrow({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 */
	findFirstOrThrow<T extends StreeplijstFindFirstOrThrowArgs>(
		args?: Prisma.SelectSubset<T, StreeplijstFindFirstOrThrowArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Find zero or more Streeplijsts that matches the filter.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstFindManyArgs} args - Arguments to filter and select certain fields only.
	 * @example
	 * // Get all Streeplijsts
	 * const streeplijsts = await prisma.streeplijst.findMany()
	 *
	 * // Get first 10 Streeplijsts
	 * const streeplijsts = await prisma.streeplijst.findMany({ take: 10 })
	 *
	 * // Only select the `id`
	 * const streeplijstWithIdOnly = await prisma.streeplijst.findMany({ select: { id: true } })
	 *
	 */
	findMany<T extends StreeplijstFindManyArgs>(
		args?: Prisma.SelectSubset<T, StreeplijstFindManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>>

	/**
	 * Create a Streeplijst.
	 * @param {StreeplijstCreateArgs} args - Arguments to create a Streeplijst.
	 * @example
	 * // Create one Streeplijst
	 * const Streeplijst = await prisma.streeplijst.create({
	 *   data: {
	 *     // ... data to create a Streeplijst
	 *   }
	 * })
	 *
	 */
	create<T extends StreeplijstCreateArgs>(
		args: Prisma.SelectSubset<T, StreeplijstCreateArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Create many Streeplijsts.
	 * @param {StreeplijstCreateManyArgs} args - Arguments to create many Streeplijsts.
	 * @example
	 * // Create many Streeplijsts
	 * const streeplijst = await prisma.streeplijst.createMany({
	 *   data: [
	 *     // ... provide data here
	 *   ]
	 * })
	 *
	 */
	createMany<T extends StreeplijstCreateManyArgs>(
		args?: Prisma.SelectSubset<T, StreeplijstCreateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Delete a Streeplijst.
	 * @param {StreeplijstDeleteArgs} args - Arguments to delete one Streeplijst.
	 * @example
	 * // Delete one Streeplijst
	 * const Streeplijst = await prisma.streeplijst.delete({
	 *   where: {
	 *     // ... filter to delete one Streeplijst
	 *   }
	 * })
	 *
	 */
	delete<T extends StreeplijstDeleteArgs>(
		args: Prisma.SelectSubset<T, StreeplijstDeleteArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Update one Streeplijst.
	 * @param {StreeplijstUpdateArgs} args - Arguments to update one Streeplijst.
	 * @example
	 * // Update one Streeplijst
	 * const streeplijst = await prisma.streeplijst.update({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	update<T extends StreeplijstUpdateArgs>(
		args: Prisma.SelectSubset<T, StreeplijstUpdateArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Delete zero or more Streeplijsts.
	 * @param {StreeplijstDeleteManyArgs} args - Arguments to filter Streeplijsts to delete.
	 * @example
	 * // Delete a few Streeplijsts
	 * const { count } = await prisma.streeplijst.deleteMany({
	 *   where: {
	 *     // ... provide filter here
	 *   }
	 * })
	 *
	 */
	deleteMany<T extends StreeplijstDeleteManyArgs>(
		args?: Prisma.SelectSubset<T, StreeplijstDeleteManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Update zero or more Streeplijsts.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstUpdateManyArgs} args - Arguments to update one or more rows.
	 * @example
	 * // Update many Streeplijsts
	 * const streeplijst = await prisma.streeplijst.updateMany({
	 *   where: {
	 *     // ... provide filter here
	 *   },
	 *   data: {
	 *     // ... provide data here
	 *   }
	 * })
	 *
	 */
	updateMany<T extends StreeplijstUpdateManyArgs>(
		args: Prisma.SelectSubset<T, StreeplijstUpdateManyArgs<ExtArgs>>,
	): Prisma.PrismaPromise<Prisma.BatchPayload>

	/**
	 * Create or update one Streeplijst.
	 * @param {StreeplijstUpsertArgs} args - Arguments to update or create a Streeplijst.
	 * @example
	 * // Update or create a Streeplijst
	 * const streeplijst = await prisma.streeplijst.upsert({
	 *   create: {
	 *     // ... data to create a Streeplijst
	 *   },
	 *   update: {
	 *     // ... in case it already exists, update
	 *   },
	 *   where: {
	 *     // ... the filter for the Streeplijst we want to update
	 *   }
	 * })
	 */
	upsert<T extends StreeplijstUpsertArgs>(
		args: Prisma.SelectSubset<T, StreeplijstUpsertArgs<ExtArgs>>,
	): Prisma.Prisma__StreeplijstClient<
		runtime.Types.Result.GetResult<Prisma.$StreeplijstPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
		never,
		ExtArgs,
		GlobalOmitOptions
	>

	/**
	 * Count the number of Streeplijsts.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstCountArgs} args - Arguments to filter Streeplijsts to count.
	 * @example
	 * // Count the number of Streeplijsts
	 * const count = await prisma.streeplijst.count({
	 *   where: {
	 *     // ... the filter for the Streeplijsts we want to count
	 *   }
	 * })
	 **/
	count<T extends StreeplijstCountArgs>(
		args?: Prisma.Subset<T, StreeplijstCountArgs>,
	): Prisma.PrismaPromise<
		T extends runtime.Types.Utils.Record<'select', any>
			? T['select'] extends true
				? number
				: Prisma.GetScalarType<T['select'], StreeplijstCountAggregateOutputType>
			: number
	>

	/**
	 * Allows you to perform aggregations operations on a Streeplijst.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
	 * @example
	 * // Ordered by age ascending
	 * // Where email contains prisma.io
	 * // Limited to the 10 users
	 * const aggregations = await prisma.user.aggregate({
	 *   _avg: {
	 *     age: true,
	 *   },
	 *   where: {
	 *     email: {
	 *       contains: "prisma.io",
	 *     },
	 *   },
	 *   orderBy: {
	 *     age: "asc",
	 *   },
	 *   take: 10,
	 * })
	 **/
	aggregate<T extends StreeplijstAggregateArgs>(
		args: Prisma.Subset<T, StreeplijstAggregateArgs>,
	): Prisma.PrismaPromise<GetStreeplijstAggregateType<T>>

	/**
	 * Group by Streeplijst.
	 * Note, that providing `undefined` is treated as the value not being there.
	 * Read more here: https://pris.ly/d/null-undefined
	 * @param {StreeplijstGroupByArgs} args - Group by arguments.
	 * @example
	 * // Group by city, order by createdAt, get count
	 * const result = await prisma.user.groupBy({
	 *   by: ['city', 'createdAt'],
	 *   orderBy: {
	 *     createdAt: true
	 *   },
	 *   _count: {
	 *     _all: true
	 *   },
	 * })
	 *
	 **/
	groupBy<
		T extends StreeplijstGroupByArgs,
		HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
		OrderByArg extends Prisma.True extends HasSelectOrTake
			? { orderBy: StreeplijstGroupByArgs['orderBy'] }
			: { orderBy?: StreeplijstGroupByArgs['orderBy'] },
		OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
		ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
		ByValid extends Prisma.Has<ByFields, OrderFields>,
		HavingFields extends Prisma.GetHavingFields<T['having']>,
		HavingValid extends Prisma.Has<ByFields, HavingFields>,
		ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
		InputErrors extends ByEmpty extends Prisma.True
			? `Error: "by" must not be empty.`
			: HavingValid extends Prisma.False
				? {
						[P in HavingFields]: P extends ByFields
							? never
							: P extends string
								? `Error: Field "${P}" used in "having" needs to be provided in "by".`
								: [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
					}[HavingFields]
				: 'take' extends Prisma.Keys<T>
					? 'orderBy' extends Prisma.Keys<T>
						? ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields]
						: 'Error: If you provide "take", you also need to provide "orderBy"'
					: 'skip' extends Prisma.Keys<T>
						? 'orderBy' extends Prisma.Keys<T>
							? ByValid extends Prisma.True
								? {}
								: {
										[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
									}[OrderFields]
							: 'Error: If you provide "skip", you also need to provide "orderBy"'
						: ByValid extends Prisma.True
							? {}
							: {
									[P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
								}[OrderFields],
	>(
		args: Prisma.SubsetIntersection<T, StreeplijstGroupByArgs, OrderByArg> & InputErrors,
	): {} extends InputErrors ? GetStreeplijstGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
	/**
	 * Fields of the Streeplijst model
	 */
	readonly fields: StreeplijstFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for Streeplijst.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StreeplijstClient<
	T,
	Null = never,
	ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
	GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
	readonly [Symbol.toStringTag]: 'PrismaPromise'
	treasurer<T extends Prisma.Streeplijst$treasurerArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Streeplijst$treasurerArgs<ExtArgs>>,
	): Prisma.Prisma__UserClient<
		runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | null,
		null,
		ExtArgs,
		GlobalOmitOptions
	>
	sales<T extends Prisma.Streeplijst$salesArgs<ExtArgs> = {}>(
		args?: Prisma.Subset<T, Prisma.Streeplijst$salesArgs<ExtArgs>>,
	): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null>
	/**
	 * Attaches callbacks for the resolution and/or rejection of the Promise.
	 * @param onfulfilled The callback to execute when the Promise is resolved.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of which ever callback is executed.
	 */
	then<TResult1 = T, TResult2 = never>(
		onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
		onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
	): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
	/**
	 * Attaches a callback for only the rejection of the Promise.
	 * @param onrejected The callback to execute when the Promise is rejected.
	 * @returns A Promise for the completion of the callback.
	 */
	catch<TResult = never>(
		onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
	): runtime.Types.Utils.JsPromise<T | TResult>
	/**
	 * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
	 * resolved value cannot be modified from the callback.
	 * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
	 * @returns A Promise for the completion of the callback.
	 */
	finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the Streeplijst model
 */
export interface StreeplijstFieldRefs {
	readonly id: Prisma.FieldRef<'Streeplijst', 'Int'>
	readonly createdAt: Prisma.FieldRef<'Streeplijst', 'DateTime'>
	readonly updatedAt: Prisma.FieldRef<'Streeplijst', 'DateTime'>
	readonly startDate: Prisma.FieldRef<'Streeplijst', 'DateTime'>
	readonly endDate: Prisma.FieldRef<'Streeplijst', 'DateTime'>
	readonly userId: Prisma.FieldRef<'Streeplijst', 'Int'>
	readonly notes: Prisma.FieldRef<'Streeplijst', 'String'>
}

// Custom InputTypes
/**
 * Streeplijst findUnique
 */
export type StreeplijstFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * Filter, which Streeplijst to fetch.
	 */
	where: Prisma.StreeplijstWhereUniqueInput
}

/**
 * Streeplijst findUniqueOrThrow
 */
export type StreeplijstFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	{
		/**
		 * Select specific fields to fetch from the Streeplijst
		 */
		select?: Prisma.StreeplijstSelect<ExtArgs> | null
		/**
		 * Omit specific fields from the Streeplijst
		 */
		omit?: Prisma.StreeplijstOmit<ExtArgs> | null
		/**
		 * Choose, which related nodes to fetch as well
		 */
		include?: Prisma.StreeplijstInclude<ExtArgs> | null
		/**
		 * Filter, which Streeplijst to fetch.
		 */
		where: Prisma.StreeplijstWhereUniqueInput
	}

/**
 * Streeplijst findFirst
 */
export type StreeplijstFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * Filter, which Streeplijst to fetch.
	 */
	where?: Prisma.StreeplijstWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Streeplijsts to fetch.
	 */
	orderBy?: Prisma.StreeplijstOrderByWithRelationInput | Prisma.StreeplijstOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for searching for Streeplijsts.
	 */
	cursor?: Prisma.StreeplijstWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Streeplijsts from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Streeplijsts.
	 */
	skip?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
	 *
	 * Filter by unique combinations of Streeplijsts.
	 */
	distinct?: Prisma.StreeplijstScalarFieldEnum | Prisma.StreeplijstScalarFieldEnum[]
}

/**
 * Streeplijst findFirstOrThrow
 */
export type StreeplijstFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
	{
		/**
		 * Select specific fields to fetch from the Streeplijst
		 */
		select?: Prisma.StreeplijstSelect<ExtArgs> | null
		/**
		 * Omit specific fields from the Streeplijst
		 */
		omit?: Prisma.StreeplijstOmit<ExtArgs> | null
		/**
		 * Choose, which related nodes to fetch as well
		 */
		include?: Prisma.StreeplijstInclude<ExtArgs> | null
		/**
		 * Filter, which Streeplijst to fetch.
		 */
		where?: Prisma.StreeplijstWhereInput
		/**
		 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
		 *
		 * Determine the order of Streeplijsts to fetch.
		 */
		orderBy?: Prisma.StreeplijstOrderByWithRelationInput | Prisma.StreeplijstOrderByWithRelationInput[]
		/**
		 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
		 *
		 * Sets the position for searching for Streeplijsts.
		 */
		cursor?: Prisma.StreeplijstWhereUniqueInput
		/**
		 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
		 *
		 * Take `±n` Streeplijsts from the position of the cursor.
		 */
		take?: number
		/**
		 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
		 *
		 * Skip the first `n` Streeplijsts.
		 */
		skip?: number
		/**
		 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
		 *
		 * Filter by unique combinations of Streeplijsts.
		 */
		distinct?: Prisma.StreeplijstScalarFieldEnum | Prisma.StreeplijstScalarFieldEnum[]
	}

/**
 * Streeplijst findMany
 */
export type StreeplijstFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * Filter, which Streeplijsts to fetch.
	 */
	where?: Prisma.StreeplijstWhereInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
	 *
	 * Determine the order of Streeplijsts to fetch.
	 */
	orderBy?: Prisma.StreeplijstOrderByWithRelationInput | Prisma.StreeplijstOrderByWithRelationInput[]
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
	 *
	 * Sets the position for listing Streeplijsts.
	 */
	cursor?: Prisma.StreeplijstWhereUniqueInput
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Take `±n` Streeplijsts from the position of the cursor.
	 */
	take?: number
	/**
	 * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
	 *
	 * Skip the first `n` Streeplijsts.
	 */
	skip?: number
	distinct?: Prisma.StreeplijstScalarFieldEnum | Prisma.StreeplijstScalarFieldEnum[]
}

/**
 * Streeplijst create
 */
export type StreeplijstCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * The data needed to create a Streeplijst.
	 */
	data: Prisma.XOR<Prisma.StreeplijstCreateInput, Prisma.StreeplijstUncheckedCreateInput>
}

/**
 * Streeplijst createMany
 */
export type StreeplijstCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to create many Streeplijsts.
	 */
	data: Prisma.StreeplijstCreateManyInput | Prisma.StreeplijstCreateManyInput[]
	skipDuplicates?: boolean
}

/**
 * Streeplijst update
 */
export type StreeplijstUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * The data needed to update a Streeplijst.
	 */
	data: Prisma.XOR<Prisma.StreeplijstUpdateInput, Prisma.StreeplijstUncheckedUpdateInput>
	/**
	 * Choose, which Streeplijst to update.
	 */
	where: Prisma.StreeplijstWhereUniqueInput
}

/**
 * Streeplijst updateMany
 */
export type StreeplijstUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * The data used to update Streeplijsts.
	 */
	data: Prisma.XOR<Prisma.StreeplijstUpdateManyMutationInput, Prisma.StreeplijstUncheckedUpdateManyInput>
	/**
	 * Filter which Streeplijsts to update
	 */
	where?: Prisma.StreeplijstWhereInput
	/**
	 * Limit how many Streeplijsts to update.
	 */
	limit?: number
}

/**
 * Streeplijst upsert
 */
export type StreeplijstUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * The filter to search for the Streeplijst to update in case it exists.
	 */
	where: Prisma.StreeplijstWhereUniqueInput
	/**
	 * In case the Streeplijst found by the `where` argument doesn't exist, create a new Streeplijst with this data.
	 */
	create: Prisma.XOR<Prisma.StreeplijstCreateInput, Prisma.StreeplijstUncheckedCreateInput>
	/**
	 * In case the Streeplijst was found with the provided `where` argument, update it with this data.
	 */
	update: Prisma.XOR<Prisma.StreeplijstUpdateInput, Prisma.StreeplijstUncheckedUpdateInput>
}

/**
 * Streeplijst delete
 */
export type StreeplijstDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
	/**
	 * Filter which Streeplijst to delete.
	 */
	where: Prisma.StreeplijstWhereUniqueInput
}

/**
 * Streeplijst deleteMany
 */
export type StreeplijstDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Filter which Streeplijsts to delete
	 */
	where?: Prisma.StreeplijstWhereInput
	/**
	 * Limit how many Streeplijsts to delete.
	 */
	limit?: number
}

/**
 * Streeplijst.treasurer
 */
export type Streeplijst$treasurerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the User
	 */
	select?: Prisma.UserSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the User
	 */
	omit?: Prisma.UserOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.UserInclude<ExtArgs> | null
	where?: Prisma.UserWhereInput
}

/**
 * Streeplijst.sales
 */
export type Streeplijst$salesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Journal
	 */
	select?: Prisma.JournalSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Journal
	 */
	omit?: Prisma.JournalOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.JournalInclude<ExtArgs> | null
	where?: Prisma.JournalWhereInput
	orderBy?: Prisma.JournalOrderByWithRelationInput | Prisma.JournalOrderByWithRelationInput[]
	cursor?: Prisma.JournalWhereUniqueInput
	take?: number
	skip?: number
	distinct?: Prisma.JournalScalarFieldEnum | Prisma.JournalScalarFieldEnum[]
}

/**
 * Streeplijst without action
 */
export type StreeplijstDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
	/**
	 * Select specific fields to fetch from the Streeplijst
	 */
	select?: Prisma.StreeplijstSelect<ExtArgs> | null
	/**
	 * Omit specific fields from the Streeplijst
	 */
	omit?: Prisma.StreeplijstOmit<ExtArgs> | null
	/**
	 * Choose, which related nodes to fetch as well
	 */
	include?: Prisma.StreeplijstInclude<ExtArgs> | null
}
